/**
 * FULL-GAME SAFETY GUARDS (Sprint 008 · Phase 10/14.3). Source + artifact guards that the full-game system
 * stays honest: the engine never touches the market, the report leads with the game (Overview default) and
 * keeps the market a labelled comparison, and the daily artifact never fabricates numbers for an
 * unavailable game.
 *
 * Run: npx tsx --test src/lib/mlb/full-game/report-safety.test.mjs
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const app = process.cwd();
const read = (rel) => fs.readFileSync(path.join(app, rel), "utf8");

test("the engine is market-independent — no sportsbook value drives any simulated output", () => {
  for (const f of [
    "src/lib/mlb/full-game/engine.ts",
    "src/lib/mlb/full-game/plate-appearance.ts",
    "src/lib/mlb/full-game/simulate.ts",
  ]) {
    const src = read(f);
    assert.ok(!/moneyline|noVigProb|impliedProb|marketProb|team-markets/i.test(src), `${f} must not reference the market`);
  }
});

test("the board adapter documents the pregame families it does NOT have (never faked)", () => {
  const src = read("src/lib/mlb/full-game/board-adapter.ts");
  for (const fam of ["confirmed_batting_order", "park_run_factors", "weather", "batter_handedness_splits"]) {
    assert.ok(src.includes(fam), `missing-family "${fam}" must be marked`);
  }
  // The lineup fallback is a documented replacement-level filler, never a real player projection.
  assert.match(src, /Lineup fallback/, "padded lineup spots use a clearly-labelled fallback");
});

test("the report leads with the game — Overview is the default tab", () => {
  const src = read("src/components/game/mlb-full-game-report.tsx");
  assert.match(src, /useState<TabKey>\("overview"\)/, "Overview is the default tab");
  // The dense player/prop report is rendered only under the secondary Players tab, not Overview.
  assert.match(src, /tab === "players" &&[\s\S]*deepDive/, "the player/prop deep-dive lives under the Players tab");
});

test("the report keeps the market a labelled comparison, never the headline", () => {
  const src = read("src/components/game/mlb-full-game-report.tsx");
  assert.match(src, /never an input to our simulation/, "market is explicitly labelled comparison-only");
  assert.match(src, /do not claim to beat it|not.*validated to out-predict/i, "no market-beating claim");
  // No Bank Builder / Moonshot eligibility in the game-first component (it belongs in the deep-dive tab).
  assert.ok(!/Bank Builder|Moonshot/i.test(src), "no product eligibility in the game-first report");
});

test("if the July-24 full-game artifact exists, it is internally consistent and never fabricates", () => {
  const p = path.join(app, "public/data/mlb/full-game-simulations/2026-07-24.json");
  if (!fs.existsSync(p)) return; // artifact is generated by the daily chain; absence is not a failure here
  const a = JSON.parse(fs.readFileSync(p, "utf8"));
  assert.equal(a.sport, "mlb");
  assert.ok(Array.isArray(a.games) && a.games.length > 0);
  const seenPk = new Set();
  for (const g of a.games) {
    assert.ok(g.gamePk != null, "every game keyed by gamePk");
    assert.ok(!seenPk.has(g.gamePk), "gamePk is unique (doubleheader-safe)");
    seenPk.add(g.gamePk);
    if (g.status === "unavailable") {
      assert.equal(g.winProbability, null);
      assert.equal(g.runs, null);
      assert.equal(g.runCount, 0);
    } else {
      assert.equal(g.runCount, a.runCount, "ready/degraded games ran the full run count");
      assert.ok(Math.abs(g.winProbability.away + g.winProbability.home - 1) < 0.005, "win prob conserves");
      assert.ok(g.totalRuns.p10 <= g.totalRuns.median && g.totalRuns.median <= g.totalRuns.p90);
      // The market, when present, is a separate comparison object — not fused into the simulated outputs.
      if (g.market) assert.ok("moneyline" in g.market, "market is carried as a distinct comparison layer");
    }
  }
});
