/**
 * Multi-sport readiness gate — the reusable internal contract (Program 144 · Release H).
 *
 * THE RULE THIS ENCODES. A sport may be called publicly live ONLY when every stage of its pipeline
 * operates end to end. A schedule feed, an archive, an odds provider, a nav tab or an empty hub is
 * not activity — that is how UFC ended up presented beside live MLB (Program 139), and this
 * contract is the mechanical form of the fix. Public activation additionally requires explicit
 * founder approval; passing the gate is NECESSARY, never sufficient.
 *
 * Twelve stages, each with a proof requirement. UNPROVEN is the default everywhere: a stage with
 * no recorded evidence is not "probably fine", it is unproven. The gate is data — assessments are
 * committed as fixtures under this contract and re-evaluated as evidence lands, so "how far is
 * NFL?" always has one answer with receipts rather than an optimistic guess.
 */

export const SPORT_GATE_VERSION = 1;

/** The pipeline stages, in dependency order. Every one must be PROVEN for LIVE eligibility. */
export const GATE_STAGES = Object.freeze([
  { id: "schedule", name: "Schedule/event discovery", proof: "daily schedule artifact from an approved source, date-correct in ET" },
  { id: "identity", name: "Team/player identity + assets", proof: "canonical ids resolving through the identity components with fallbacks" },
  { id: "data", name: "Required stats/context data", proof: "the model's input fields present for a full slate, no paid call outside budget" },
  { id: "markets", name: "Market/odds ingestion", proof: "credit-guarded ingestion producing de-vigged implied probabilities" },
  { id: "model", name: "Model/simulation", proof: "a versioned model producing per-event outputs from pregame inputs only" },
  { id: "calibration", name: "Calibration/validation", proof: "a preregistered backtest against settled results — the MLB bar (Brier vs market), not a smaller one" },
  { id: "qualification", name: "Pick qualification policy", proof: "a written policy with thresholds, applied by code, with no-play as a first-class outcome" },
  { id: "products", name: "Product generation", proof: "boards/cards generated by scheduled automation with the product-state contract" },
  { id: "publication", name: "Publication + freshness", proof: "public surfaces derive freshness from the product's own artifact" },
  { id: "settlement", name: "Official settlement", proof: "grading from official results with lineage stamps, quarantine on ambiguity" },
  { id: "monitoring", name: "Monitoring + alerting", proof: "the evidence ledger and watchdog cover the sport's chain" },
  { id: "owner", name: "Accountable daily owner", proof: "a named owner (automation + human escalation) for the daily run" },
]);

export const STAGE_STATUS = Object.freeze(["PROVEN", "PARTIAL", "UNPROVEN", "BLOCKED_EXTERNAL"]);

/** Public-facing maturity, derived — never asserted directly. */
export const SPORT_MATURITY = Object.freeze([
  "LIVE_ELIGIBLE",     // every stage PROVEN (founder activation still separate)
  "SEASONAL_READY",    // all PROVEN except stages that require an in-season slate to demonstrate
  "SCAFFOLDED",        // some stages PROVEN/PARTIAL, core stages missing
  "HISTORICAL_ONLY",   // settlement-grade archive exists; no forward pipeline
  "NOT_STARTED",
]);

/** Stages that can only be PROVEN while the competition is running. */
const IN_SEASON_ONLY = new Set(["products", "publication", "monitoring"]);

/**
 * Derive maturity from a stage assessment. Pure; assessments are data.
 * @param {Record<string, {status: string, evidence?: string|null, blocker?: string|null}>} stages
 * @param {{historicalArchive?: boolean, inSeason?: boolean}} [flags]
 */
export function deriveSportMaturity(stages, { historicalArchive = false, inSeason = true } = {}) {
  const get = (id) => stages[id]?.status ?? "UNPROVEN";
  for (const s of GATE_STAGES) {
    const st = get(s.id);
    if (!STAGE_STATUS.includes(st)) throw new Error(`sport-gate: invalid status ${st} for ${s.id}`);
  }

  const allProven = GATE_STAGES.every((s) => get(s.id) === "PROVEN");
  if (allProven) return "LIVE_ELIGIBLE";

  // Off-season: the only unproven stages are those that need a live slate to demonstrate.
  const offSeasonGaps = GATE_STAGES.filter((s) => get(s.id) !== "PROVEN");
  if (!inSeason && offSeasonGaps.every((s) => IN_SEASON_ONLY.has(s.id))) return "SEASONAL_READY";

  const provenCount = GATE_STAGES.filter((s) => get(s.id) === "PROVEN").length;
  if (provenCount > 0 || GATE_STAGES.some((s) => get(s.id) === "PARTIAL")) return "SCAFFOLDED";
  if (historicalArchive) return "HISTORICAL_ONLY";
  return "NOT_STARTED";
}

/** True only when public activation may even be REQUESTED. Founder approval is still separate. */
export function publicActivationEligible(stages, flags) {
  return deriveSportMaturity(stages, flags) === "LIVE_ELIGIBLE";
}

/**
 * The honest gap list — what remains, in dependency order, each with its proof requirement.
 * This is what "shortest honest path to launch" means mechanically.
 */
export function remainingPath(stages) {
  return GATE_STAGES
    .filter((s) => (stages[s.id]?.status ?? "UNPROVEN") !== "PROVEN")
    .map((s) => ({
      stage: s.id,
      name: s.name,
      status: stages[s.id]?.status ?? "UNPROVEN",
      requiredProof: s.proof,
      blocker: stages[s.id]?.blocker ?? null,
    }));
}
