#!/usr/bin/env bash
# Commit and push GENERATED artifacts without losing a run to a same-day conflict (P257 pipeline review).
#
#   GENERATED_PATHS="app/public/data/parlays/ data/internal/products/" \
#     bash scripts/ci/commit-generated.sh "auto: daily products 2026-09-11 [skip ci]"
#
# Why: two runs regenerating the same day's derived files (the lab ledger, forward coverage, today's receipt)
# both commit; the second's rebase hits a content conflict and the whole run fails — 2026-09-11 15:13 UTC
# (daily-products), and earlier in epl-matchweek and auto-refresh. For a REGENERATED file, the run that
# pushes last has the freshest derivation, so a conflict inside GENERATED_PATHS resolves to this run's copy.
#
# Guard rails:
#   · only paths under GENERATED_PATHS may be auto-resolved; any other conflict aborts the rebase and fails loud
#   · the protected money files are NEVER auto-resolved, whatever GENERATED_PATHS says
#   · the caller stages; this script only commits what is staged, retries the push, and never force-pushes
set -euo pipefail
MSG="${1:?commit message required}"
: "${GENERATED_PATHS:?GENERATED_PATHS required (space-separated path prefixes)}"
# v1.7 shadow-integrity audit: a shadow day file is a FIRST-PUBLICATION-WINS artifact. Two runs that both
# created it would otherwise be resolved to the later copy — the S7 rewrite in a new place — so it is
# refused like the money files, whatever GENERATED_PATHS says (docs/V17_WORKFLOW_AUDIT.md W2).
PROTECTED_RE='(^|/)mr-dub/(portfolio|ledger|daily-summary|banked-ladders)\.json$|(^|/)data/internal/products/selector-shadow/'

if git diff --cached --quiet; then echo "commit-generated: nothing staged"; exit 0; fi
git commit -q -m "$MSG"

allowed() { local f="$1"; [[ "$f" =~ $PROTECTED_RE ]] && return 1; for p in $GENERATED_PATHS; do [[ "$f" == "$p"* ]] && return 0; done; return 1; }

for attempt in 1 2 3 4 5; do
  if git push -q origin HEAD:main; then echo "commit-generated: pushed (attempt $attempt)"; exit 0; fi
  echo "commit-generated: push rejected (attempt $attempt) — rebasing onto origin/main"
  git fetch -q origin main
  # --autostash (docs/V17_WORKFLOW_AUDIT.md W1): the caller unstages stamp-only files, which leaves them
  # MODIFIED in the worktree, and `git rebase` refuses a dirty tree ("cannot rebase: You have unstaged
  # changes") — silently, behind the redirect. Run 35630279965 (2026-09-21 17:10Z) rebased five times
  # without moving and failed. The autostash carries the unstaged edits across the rebase.
  if git rebase -q --autostash origin/main >/dev/null 2>&1; then continue; fi
  # A content conflict. During a rebase, "theirs" is the commit being replayed — this run's version.
  while true; do
    conflicted=$(git diff --name-only --diff-filter=U)
    [ -z "$conflicted" ] && break
    for f in $conflicted; do
      if allowed "$f"; then
        git checkout --theirs -- "$f" && git add -- "$f"
        echo "commit-generated: $f regenerated by two runs — this run's (later) copy kept"
      else
        echo "::error::commit-generated: conflict on $f, which is not a regenerable path — aborting, nothing forced"
        git rebase --abort; exit 1
      fi
    done
    if ! GIT_EDITOR=true git rebase --continue >/dev/null 2>&1; then
      [ -n "$(git diff --name-only --diff-filter=U)" ] && continue
      git rebase --skip >/dev/null 2>&1 || true   # our commit became empty: the other run already published it
    fi
    [ -d "$(git rev-parse --git-path rebase-merge)" ] || [ -d "$(git rev-parse --git-path rebase-apply)" ] || break
  done
  sleep $((attempt * 3))
done
echo "::error::commit-generated: push never landed after 5 attempts"; exit 1
