"use client";
/**
 * RiskSectionSpread — public Parlay Lab Suggested-mode layout that
 * groups slips into four sections (Low / Medium / High / Longshot).
 *
 * Two data paths:
 *
 *   1. **Server-bucketed (preferred)** — `sections` prop is populated
 *      from the optimizer snapshot's `publicRiskSections.<section>.<sport>`,
 *      generated by `pipeline.parlay_optimizer.generate_public_risk_sections`.
 *      Every slip in here was produced under the strict
 *      "BOTH combined odds AND leg count must fall in the section's
 *      range" rule.
 *   2. **Client-fallback** — when the snapshot predates the server-side
 *      selector (no `publicRiskSections` key), we re-bucket the visible
 *      `slips` array client-side using `groupSlipsByRiskSection`. Slips
 *      that don't honor both the odds AND leg-count bands land in the
 *      excluded bucket and are not displayed under any section.
 *
 * Headers carry the user-spec'd "X–Y legs · odds range" subtitle so
 * the boundaries the optimizer enforced are visible. Sport-bucket
 * label and slate-date context come from the page-level slate strip,
 * so the section headers stay clean.
 *
 * Honest empty state: each section explains *why* it's empty (single-
 * game NBA slate, sport filter starved the pool, etc.) without ever
 * implying fabricated alternatives.
 *
 * Pure presentation. Optimizer payload, settlement, era filter, and
 * audit policy are untouched.
 */
import ParlayTicketCard from "./parlay-ticket-card";
import {
  RISK_SECTION_ORDER,
  getRiskSectionDisplay,
  groupSlipsByRiskSection,
  type RiskSectionKey,
} from "@/lib/parlay-risk-sections";
import type {
  ParlayLeg,
  ParlaySlip,
  SuggestedSport,
} from "@/lib/parlay-suggested";
import type { CalibrationTable } from "@/lib/confidence-calibration-rules";

export interface RiskSectionSpreadProps {
  /** Fallback path: visible slips when `sections` is not provided
   *  (legacy snapshots). The component re-buckets these client-side
   *  using the strict odds + legs rule. */
  slips?: ReadonlyArray<ParlaySlip>;
  /** Preferred path: pre-bucketed slips per section, generated by the
   *  pipeline's `generate_public_risk_sections` and filtered to the
   *  active sport before being passed in. When provided, slips are
   *  rendered as-is (server already enforced the both-must-match rule)
   *  and `slips` is ignored. */
  sections?: Partial<Record<RiskSectionKey, ReadonlyArray<ParlaySlip>>>;
  /** Active sport — surfaces in the section empty-state copy. */
  sport: SuggestedSport;
  /** Honest source classification surfaced as "Saved pregame" on each
   *  ticket. */
  source: "snapshot" | "graded";
  /** Calibration table threaded into every ticket card. */
  calibrationTable?: CalibrationTable;
  /** Leg click handler — opens the recent-form drawer. */
  onLegClick?: (leg: ParlayLeg) => void;
}

/** When two slips' scores differ by less than this, prefer the one
 *  that contains at least one star leg. Mild, transparent, never
 *  surfaces a weaker slip over a better one when scores diverge. */
const STAR_TIEBREAKER_THRESHOLD = 0.05;

function _slipHasStar(slip: ParlaySlip): boolean {
  return slip.legs.some(
    (l) => l.isStar === true || (l.starTier && l.starTier !== "none"),
  );
}

function _sortWithStarTiebreaker(
  slips: ReadonlyArray<ParlaySlip>,
): ParlaySlip[] {
  const arr = [...slips];
  arr.sort((a, b) => {
    const scoreGap = (b.score ?? 0) - (a.score ?? 0);
    if (Math.abs(scoreGap) >= STAR_TIEBREAKER_THRESHOLD) return scoreGap;
    const aHasStar = _slipHasStar(a);
    const bHasStar = _slipHasStar(b);
    if (aHasStar && !bHasStar) return -1;
    if (bHasStar && !aHasStar) return 1;
    return scoreGap;
  });
  return arr;
}

function _bucketSlipsClientSide(
  slips: ReadonlyArray<ParlaySlip>,
): Record<RiskSectionKey, ParlaySlip[]> {
  const { sections } = groupSlipsByRiskSection(slips);
  const out: Record<RiskSectionKey, ParlaySlip[]> = {
    low: [], medium: [], high: [], longshot: [],
  };
  for (const { section, slips: bucketSlips } of sections) {
    out[section] = bucketSlips;
  }
  return out;
}

export default function RiskSectionSpread({
  slips,
  sections,
  sport,
  source,
  calibrationTable,
  onLegClick,
}: RiskSectionSpreadProps) {
  // Server-bucketed path wins when provided. Otherwise re-bucket the
  // visible slips client-side using the strict both-must-match rule.
  const buckets: Record<RiskSectionKey, ParlaySlip[]> = sections
    ? {
        low: [...(sections.low ?? [])],
        medium: [...(sections.medium ?? [])],
        high: [...(sections.high ?? [])],
        longshot: [...(sections.longshot ?? [])],
      }
    : _bucketSlipsClientSide(slips ?? []);

  const savedPregame = source === "snapshot";

  return (
    <div className="flex flex-col gap-5">
      {RISK_SECTION_ORDER.map((sectionKey) => {
        const display = getRiskSectionDisplay(sectionKey);
        const sectionSlips = _sortWithStarTiebreaker(buckets[sectionKey]);
        return (
          <section
            key={sectionKey}
            aria-label={`${display.label} parlays`}
            className="rounded-[10px] overflow-hidden"
            style={{
              background: "var(--gtp-card)",
              border: "1px solid var(--gtp-card-border)",
            }}
          >
            <header
              className="px-3 sm:px-4 py-3 flex flex-wrap items-baseline gap-x-3 gap-y-1"
              style={{
                background: "var(--gtp-card-sunken)",
                borderBottom: "1px solid var(--vault-rule)",
              }}
            >
              <span
                className="font-mono uppercase tracking-[0.16em]"
                style={{ color: display.accentVar, fontSize: 12 }}
              >
                {display.label}
              </span>
              <span
                className="font-mono"
                style={{ color: "var(--vault-text-mute)", fontSize: 11 }}
              >
                · {display.legRange} · {display.oddsRange}
              </span>
              <span
                className="font-mono ml-auto"
                style={{ color: "var(--vault-text-faint)", fontSize: 10 }}
              >
                {sectionSlips.length}
                {sectionSlips.length === 1 ? " parlay" : " parlays"}
              </span>
            </header>

            {sectionSlips.length === 0 ? (
              <SectionEmpty sport={sport} sectionKey={sectionKey} />
            ) : (
              <div className="px-3 sm:px-4 py-4 grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-4">
                {sectionSlips.map((slip) => (
                  <ParlayTicketCard
                    key={slip.slipId}
                    slip={slip}
                    emphasis="featured"
                    showStakeFooter
                    savedPregame={savedPregame}
                    calibrationTable={calibrationTable}
                    onLegClick={onLegClick}
                  />
                ))}
              </div>
            )}
          </section>
        );
      })}
    </div>
  );
}

function SectionEmpty({
  sport,
  sectionKey,
}: {
  sport: SuggestedSport;
  sectionKey: RiskSectionKey;
}) {
  const display = getRiskSectionDisplay(sectionKey);
  // The user spec requires honest empty copy that names *why* the
  // section is empty without implying alternatives that don't exist.
  let body: string;
  if (sport === "nba") {
    body =
      `No NBA-only ${display.legRange} parlays available right now. ` +
      `On single-game slates the model's same-game cap keeps NBA-only ` +
      `slips at 2 legs — try the Mixed or All tabs for ${display.legRange}.`;
  } else if (sport === "mlb") {
    body = `No MLB-only ${display.legRange} parlays in today's qualified pool.`;
  } else if (sport === "multi") {
    body = `No Mixed (NBA + MLB) ${display.legRange} parlays in today's qualified pool.`;
  } else {
    body =
      `No ${display.legRange} parlays in today's qualified pool that ` +
      `also land in ${display.oddsRange}.`;
  }
  return (
    <div
      className="px-3 sm:px-4 pb-5 pt-3 flex flex-col items-center text-center gap-1.5"
      style={{ minHeight: 96 }}
    >
      <p
        className="text-[12.5px] leading-relaxed"
        style={{ color: "var(--vault-text-mute)", maxWidth: 380 }}
      >
        {body}
      </p>
    </div>
  );
}
