"use client";
/**
 * RiskSectionSpread — public Parlay Lab Suggested-mode layout that
 * groups slips into four sections (Low / Medium / High / Longshot).
 *
 * Two data paths:
 *
 *   1. **Server-bucketed (preferred)** — `sections` prop is populated
 *      from the optimizer snapshot's `publicRiskSections.<section>.<sport>`,
 *      generated by `pipeline.parlay_optimizer.generate_public_risk_sections`.
 *      Every slip in here was produced under the strict
 *      "BOTH combined odds AND leg count must fall in the section's
 *      range" rule.
 *   2. **Client-fallback** — when the snapshot predates the server-side
 *      selector (no `publicRiskSections` key), we re-bucket the visible
 *      `slips` array client-side using `groupSlipsByRiskSection`. Slips
 *      that don't honor both the odds AND leg-count bands land in the
 *      excluded bucket and are not displayed under any section.
 *
 * Headers carry the user-spec'd "X–Y legs · odds range" subtitle so
 * the boundaries the optimizer enforced are visible. Sport-bucket
 * label and slate-date context come from the page-level slate strip,
 * so the section headers stay clean.
 *
 * Honest empty state: each section explains *why* it's empty (single-
 * game NBA slate, sport filter starved the pool, etc.) without ever
 * implying fabricated alternatives.
 *
 * Pure presentation. Optimizer payload, settlement, era filter, and
 * audit policy are untouched.
 */
import ParlayTicketCard from "./parlay-ticket-card";
import { useBuildMyCard } from "./build-my-card-context";
import {
  RISK_SECTION_ORDER,
  getDisplaySectionBuckets,
  getRiskSectionDisplay,
  getRiskSectionDisplaySummary,
  getEmptySectionReason,
  type RiskSectionKey,
} from "@/lib/parlay-risk-sections";
import {
  buildSectionEmptyActions,
  type ParlayLeg,
  type ParlaySlip,
  type SectionEmptyAction,
  type SuggestedSport,
} from "@/lib/parlay-suggested";
import type { CalibrationTable } from "@/lib/confidence-calibration-rules";

/** Per-section availability of the Mixed / All lanes, computed by the
 *  builder from the published sections (respecting the active game
 *  filter). Threaded down so an empty section only offers a switch
 *  action when that lane actually carries content. */
export type SectionAlternatives = Partial<
  Record<RiskSectionKey, { mixed: boolean; all: boolean }>
>;

export interface RiskSectionSpreadProps {
  /** Fallback path: visible slips when `sections` is not provided
   *  (legacy snapshots). The component re-buckets these client-side
   *  using the strict odds + legs rule. */
  slips?: ReadonlyArray<ParlaySlip>;
  /** Preferred path: pre-bucketed slips per section, generated by the
   *  pipeline's `generate_public_risk_sections` and filtered to the
   *  active sport before being passed in. When provided, slips are
   *  rendered as-is (server already enforced the both-must-match rule)
   *  and `slips` is ignored. */
  sections?: Partial<Record<RiskSectionKey, ReadonlyArray<ParlaySlip>>>;
  /** Active sport — surfaces in the section empty-state copy. */
  sport: SuggestedSport;
  /** Honest source classification surfaced as "Saved pregame" on each
   *  ticket. */
  source: "snapshot" | "graded";
  /** Calibration table threaded into every ticket card. */
  calibrationTable?: CalibrationTable;
  /** Leg click handler — opens the recent-form drawer. */
  onLegClick?: (leg: ParlayLeg) => void;
  /** PR `feature/build-my-card-selected-slips` — when true, each card
   *  renders the "Add to my card" toggle and reads/writes the
   *  BuildMyCard selection context. Opt-in: omitted everywhere except
   *  the Parlay Lab Suggested mode. */
  selectable?: boolean;
  /** Active game key (or null) — surfaces "…with this game" copy in the
   *  empty-state quick actions. */
  game?: string | null;
  /** Per-section Mixed/All lane availability for the empty-state quick
   *  actions. When omitted, empty sections render the explanation only
   *  (no switch buttons). */
  sectionAlternatives?: SectionAlternatives;
  /** Invoked when the user taps an empty-section quick action. The
   *  builder interprets the action kind (switch sport / clear filter).
   *  When omitted, no action buttons render. */
  onEmptyAction?: (action: SectionEmptyAction) => void;
}

/** When two slips' scores differ by less than this, prefer the one
 *  that contains at least one star leg. Mild, transparent, never
 *  surfaces a weaker slip over a better one when scores diverge. */
const STAR_TIEBREAKER_THRESHOLD = 0.05;

function _slipHasStar(slip: ParlaySlip): boolean {
  return slip.legs.some(
    (l) => l.isStar === true || (l.starTier && l.starTier !== "none"),
  );
}

function _sortWithStarTiebreaker(
  slips: ReadonlyArray<ParlaySlip>,
): ParlaySlip[] {
  const arr = [...slips];
  arr.sort((a, b) => {
    const scoreGap = (b.score ?? 0) - (a.score ?? 0);
    if (Math.abs(scoreGap) >= STAR_TIEBREAKER_THRESHOLD) return scoreGap;
    const aHasStar = _slipHasStar(a);
    const bHasStar = _slipHasStar(b);
    if (aHasStar && !bHasStar) return -1;
    if (bHasStar && !aHasStar) return 1;
    return scoreGap;
  });
  return arr;
}

export default function RiskSectionSpread({
  slips,
  sections,
  sport,
  source,
  calibrationTable,
  onLegClick,
  selectable = false,
  game = null,
  sectionAlternatives,
  onEmptyAction,
}: RiskSectionSpreadProps) {
  // Build My Card selection. Reads the no-op default when no provider
  // is mounted, so this is safe even on surfaces that don't opt in.
  const buildMyCard = useBuildMyCard();
  // Server-bucketed path wins when provided. Otherwise re-bucket the
  // visible slips client-side using the strict both-must-match rule.
  // Shared with the builder's "Showing N parlays" summary so the count
  // and the rendered cards always agree.
  const buckets: Record<RiskSectionKey, ParlaySlip[]> = getDisplaySectionBuckets({
    sections,
    slips: slips ?? [],
  });

  const savedPregame = source === "snapshot";
  const summary = getRiskSectionDisplaySummary(buckets);
  // A team/game/player filter is "active" only when a game is set here (the
  // builder narrows server sections by team/player upstream); used to add a
  // "clearing the filter may surface more" hint to empty-section copy.
  const hasActiveFilter = game != null && game !== "";

  return (
    <div className="flex flex-col gap-5">
      <RiskSectionSummary summary={summary} />
      {RISK_SECTION_ORDER.map((sectionKey) => {
        const display = getRiskSectionDisplay(sectionKey);
        const sectionSlips = _sortWithStarTiebreaker(buckets[sectionKey]);
        return (
          <section
            key={sectionKey}
            aria-label={`${display.label} parlays`}
            className="rounded-[10px] overflow-hidden"
            style={{
              background: "var(--gtp-card)",
              border: "1px solid var(--gtp-card-border)",
            }}
          >
            <header
              className="px-3 sm:px-4 py-3 flex flex-wrap items-baseline gap-x-3 gap-y-1"
              style={{
                background: "var(--gtp-card-sunken)",
                borderBottom: "1px solid var(--vault-rule)",
              }}
            >
              <span
                className="font-mono uppercase tracking-[0.16em]"
                style={{ color: display.accentVar, fontSize: 12 }}
              >
                {display.label}
              </span>
              <span
                className="font-mono"
                style={{ color: "var(--vault-text-mute)", fontSize: 11 }}
              >
                · {display.legRange} · {display.oddsRange}
              </span>
              <span
                className="font-mono ml-auto"
                style={{ color: "var(--vault-text-faint)", fontSize: 10 }}
              >
                {sectionSlips.length}
                {sectionSlips.length === 1 ? " parlay" : " parlays"}
              </span>
            </header>

            {sectionSlips.length === 0 ? (
              <SectionEmpty
                sport={sport}
                sectionKey={sectionKey}
                game={game}
                hasActiveFilter={hasActiveFilter}
                alternatives={sectionAlternatives?.[sectionKey]}
                onEmptyAction={onEmptyAction}
              />
            ) : (
              <div className="px-3 sm:px-4 py-4 grid grid-cols-1 lg:grid-cols-2 gap-3 lg:gap-4">
                {sectionSlips.map((slip) => (
                  <ParlayTicketCard
                    key={slip.slipId}
                    slip={slip}
                    emphasis="featured"
                    showStakeFooter
                    savedPregame={savedPregame}
                    calibrationTable={calibrationTable}
                    onLegClick={onLegClick}
                    selectable={selectable}
                    selected={selectable && buildMyCard.isSelected(slip.slipId)}
                    onToggleSelect={selectable ? buildMyCard.toggle : undefined}
                  />
                ))}
              </div>
            )}
          </section>
        );
      })}
    </div>
  );
}

/**
 * Compact, honest empty-section state (PR: empty-section clarity). A
 * full-width 96px block per empty section read as "broken"; this renders a
 * slim one-line reason instead, with an optional `<details>` "why empty?"
 * disclosure and (only when a user filter is active) clear-filter actions.
 * No padding, no fabricated cards, no claim that the shown cards win more.
 */
function SectionEmpty({
  sport,
  sectionKey,
  game,
  hasActiveFilter = false,
  alternatives,
  onEmptyAction,
}: {
  sport: SuggestedSport;
  sectionKey: RiskSectionKey;
  game?: string | null;
  hasActiveFilter?: boolean;
  alternatives?: { mixed: boolean; all: boolean };
  onEmptyAction?: (action: SectionEmptyAction) => void;
}) {
  const reason = getEmptySectionReason(sectionKey, hasActiveFilter);
  // Quick actions only when a real escape exists (an active filter to clear,
  // or a lane that genuinely carries content). The pure helper decides.
  const actions: SectionEmptyAction[] = onEmptyAction
    ? buildSectionEmptyActions({
        sport,
        game: game ?? null,
        mixedHasContent: false, // mixed is not an official Suggested lane (PR #247)
        allHasContent: alternatives?.all ?? false,
      })
    : [];

  return (
    <div className="px-3 sm:px-4 py-2.5 flex flex-wrap items-center gap-x-2 gap-y-1.5">
      <span
        aria-hidden
        className="inline-block w-1.5 h-1.5 rounded-full"
        style={{ background: "var(--vault-text-faint)" }}
      />
      <span
        className="text-[12px] leading-snug"
        style={{ color: "var(--vault-text-mute)" }}
      >
        {reason}
      </span>
      {actions.length > 0 && (
        <span className="flex flex-wrap items-center gap-1.5">
          {actions.map((action) => (
            <button
              key={action.kind}
              type="button"
              onClick={() => onEmptyAction?.(action)}
              className="font-mono uppercase tracking-[0.12em] px-2 py-0.5 rounded-full"
              style={{
                color: "var(--vault-text-mute)",
                background: "transparent",
                border: "1px solid var(--vault-rule)",
                fontSize: 10,
                cursor: "pointer",
              }}
            >
              {action.label}
            </button>
          ))}
        </span>
      )}
    </div>
  );
}

/**
 * Honest one-line summary above the risk sections: how many cards across how
 * many of the four sections, and how many sections are empty after filters.
 * States plainly that sections are not padded. Never a performance claim.
 */
function RiskSectionSummary({
  summary,
}: {
  summary: {
    displayedCards: number;
    sectionsWithCards: number;
    emptySections: number;
    totalSections: number;
  };
}) {
  const { displayedCards, sectionsWithCards, emptySections, totalSections } =
    summary;
  return (
    <div
      className="rounded-[8px] px-3.5 py-2.5 flex flex-col gap-0.5"
      style={{
        background: "var(--gtp-card-sunken)",
        border: "1px solid var(--vault-rule)",
      }}
      aria-label="Risk section summary"
    >
      <p
        className="font-mono text-[12px]"
        style={{ color: "var(--vault-text-mute)" }}
        aria-live="polite"
      >
        <span style={{ color: "var(--vault-text)", fontWeight: 600 }}>
          {displayedCards}
        </span>{" "}
        {displayedCards === 1 ? "card" : "cards"} across{" "}
        <span style={{ color: "var(--vault-text)", fontWeight: 600 }}>
          {sectionsWithCards}
        </span>{" "}
        of {totalSections} risk sections
        {emptySections > 0 ? (
          <>
            {" "}
            ·{" "}
            <span style={{ color: "var(--vault-text-faint)" }}>
              {emptySections} empty after filters
            </span>
          </>
        ) : null}
      </p>
      <p
        className="text-[11px] leading-snug"
        style={{ color: "var(--vault-text-faint)" }}
      >
        Sections are not padded — we show fewer cards when the quality gates
        (market reliability, recent form, odds), sport, variety, and volume
        filters remove the rest.
      </p>
    </div>
  );
}
