/**
 * Admin evidence ledger — the versioned truth layer under the founder command center
 * (Program 144 · Release A).
 *
 * ONE SYSTEM, EXTENDED. The repository already owns its answers in three places: the generated
 * `admin/status.json` (slate, products, workflows, money gate), the launch contract (gates,
 * departments, sports), and the internal-alpha daily artifact. What no layer did was join them with
 * an explicit STATE VOCABULARY, per-entry freshness windows, and CONTRADICTION DETECTION — so the
 * dashboard could look green simply because its newest source was green, while two sources
 * disagreed underneath. This module is that layer. It creates no new opinion about any subsystem;
 * it classifies what the owners already published, and it says so when they conflict.
 *
 * PURE BY CONSTRUCTION. Every input arrives as a parameter, including `now`. The alpha-day builder
 * learned this the hard way (PASS locally where a stale build existed, DEGRADED in CI where none
 * did); this module starts pure rather than being made pure after its first environment-dependent
 * verdict. The generator script does the file reading.
 */

import { deriveSportMaturity, remainingPath, GATE_STAGES } from "../sports/sport-gate.mjs";

export const LEDGER_SCHEMA_VERSION = 2;   // v2: sport entries derive from the twelve-stage gate
const GATE_STAGE_COUNT = GATE_STAGES.length;

/**
 * The full state vocabulary. Current health and historical exception are DIFFERENT AXES — a product
 * can be HEALTHY today with an incident last week — so states never blend the two.
 */
export const LEDGER_STATES = Object.freeze([
  "HEALTHY",          // current evidence present, fresh, and consistent
  "DEGRADED",         // functioning with a named defect or partial evidence
  "INCIDENT",         // actively wrong — a contradiction or a failing critical source
  "NO_PLAY",          // ran to completion; nothing qualified (a real answer, never a failure)
  "OFF_SEASON",       // the competition is not running; absence of activity is correct
  "PLANNED",          // designed but not yet implemented — absence is expected
  "BLOCKED_EXTERNAL", // waiting on authority/credentials/vendor outside the repository
  "STALE",            // evidence exists but is older than its freshness window
  "UNKNOWN",          // a required source is missing or unreadable — never coerced to green
  "N_A",              // the dimension does not apply to this subject
]);

const STATE = Object.fromEntries(LEDGER_STATES.map((s) => [s, s]));

/** Freshness windows (hours) per source kind. Beyond the window an entry is STALE, whatever it says. */
export const FRESHNESS_WINDOWS_H = Object.freeze({
  adminStatus: 26,     // regenerated by every daily production run
  alphaDay: 26,        // refreshed each alpha day
  workflow: 26,        // the daily chain must have run within a day
  board: 30,           // a slate artifact is same-day by definition; grace for late slates
});

const hoursBetween = (aIso, bIso) => {
  const a = Date.parse(aIso ?? ""), b = Date.parse(bIso ?? "");
  return Number.isFinite(a) && Number.isFinite(b) ? Math.abs(b - a) / 3_600_000 : null;
};

/**
 * One ledger entry. Everything the command center renders traces back to a row of this shape —
 * there is deliberately no way to add a row without naming its source and evidence.
 */
function entry({ id, subject, department = null, sport = null, state, evidence, source, asOf = null, now, windowH = null, owner = "AUTOMATION", blocker = null, remediation = null }) {
  const ageH = asOf ? hoursBetween(asOf, now) : null;
  // STALE outranks a self-reported healthy state, but never masks an INCIDENT.
  let effective = state;
  if (windowH != null && state !== STATE.INCIDENT && state !== STATE.UNKNOWN) {
    if (ageH == null) effective = STATE.UNKNOWN;
    else if (ageH > windowH) effective = STATE.STALE;
  }
  return {
    id, subject, department, sport,
    state: effective,
    declaredState: state,
    evidence, source, asOf,
    ageHours: ageH == null ? null : Math.round(ageH * 10) / 10,
    freshnessWindowHours: windowH,
    owner, blocker, remediation,
  };
}

/**
 * Contradiction checks — each is a pair of sources that MUST agree, with the disagreement the
 * dashboard used to be able to hide. A contradiction always produces an INCIDENT entry; it is the
 * one state that freshness can never soften.
 */
function detectContradictions({ adminStatus, alphaDay, boardDates, simDates, now }) {
  const found = [];
  const add = (id, subject, evidence, remediation) =>
    found.push(entry({ id: `contradiction:${id}`, subject, state: STATE.INCIDENT, evidence, source: "evidence-ledger contradiction detector", asOf: now, now, owner: "ENGINEERING", remediation }));

  // 1. A workflow that reports success while its slate artifact is absent. The Aug-3 incident
  //    shape: green automation, no product.
  const wfOk = adminStatus?.workflowHealth?.ok === true;
  const slateDate = adminStatus?.slate?.mlbSlate ?? null;
  if (wfOk && slateDate && !boardDates.includes(slateDate)) {
    add("success-without-artifact", "MLB daily chain",
      `workflowHealth reports ok for ${slateDate} but no board artifact exists for that date`,
      "inspect the generation run's artifact steps — a green run must produce its board");
  }

  // 2. A board without simulations for the same date. The Aug-6 outage shape — visible this time.
  for (const d of boardDates.slice(-2)) {
    if (!simDates.includes(d)) {
      add(`board-without-sims:${d}`, `MLB ${d}`,
        `board ${d} exists but game-simulations/${d}.json does not`,
        d === slateDate
          ? "today's simulation generation has not completed — check mlb-daily-production"
          : d === "2026-08-06"
            ? "the documented permanent Aug-6 gap (docs/AUG6_SIMULATION_GAP.md) — recorded, not pageable"
            : `historical board ${d} has no simulations — investigate when this date was generated`);
    }
  }

  // 3. The dashboard's own money gate disagreeing with the alpha artifact's protected-hash check.
  const moneyGatePass = adminStatus?.moneyGate?.pass === true;
  const alphaMoney = (alphaDay?.criteria ?? []).find((c) => c.id === "protected-money");
  if (moneyGatePass && alphaMoney && alphaMoney.result === "FAIL") {
    add("protected-state-disagreement", "Protected money",
      "admin/status.json moneyGate passes while the alpha-day observer reports a protected-hash divergence",
      "STOP — two independent monitors disagree about the money. Verify the pinned md5s by hand before anything else");
  }

  // 4. An alpha day claiming PASS while any of its own criteria FAILED.
  if (alphaDay?.verdict === "PASS" && (alphaDay.criteria ?? []).some((c) => c.result === "FAIL")) {
    add("alpha-verdict-inconsistent", "Internal alpha",
      "alpha-day verdict is PASS but at least one criterion is FAIL",
      "the alpha generator's verdict rule regressed — its own tests should have caught this");
  }

  return found;
}

/**
 * Build the ledger. All parameters are data; nothing is read from disk or the clock here.
 *
 * @param {object} o
 * @param {object|null} o.adminStatus   parsed admin/status.json
 * @param {object|null} o.alphaDay      parsed ops/internal-alpha/latest.json
 * @param {Array}       o.gates         buildLaunchGates() output
 * @param {string[]}    o.boardDates    dates with a board artifact (sorted ascending)
 * @param {string[]}    o.simDates      dates with a game-simulations artifact
 * @param {string}      o.now           ISO instant the generator ran
 */
export function buildEvidenceLedger({ adminStatus = null, alphaDay = null, gates = [], boardDates = [], simDates = [], sportAssessments = {}, now }) {
  if (!now) throw new Error("evidence-ledger: `now` is required — the ledger never reads the clock itself");
  const entries = [];

  // ── Daily production chain ──────────────────────────────────────────────────────────────────
  if (!adminStatus) {
    entries.push(entry({ id: "daily-chain", subject: "MLB daily chain", department: "operations", sport: "mlb", state: STATE.UNKNOWN, evidence: "admin/status.json missing or unreadable", source: "admin/status.json", now, owner: "ENGINEERING" }));
  } else {
    const wf = adminStatus.workflowHealth ?? {};
    entries.push(entry({
      id: "daily-chain", subject: "MLB daily chain", department: "operations", sport: "mlb",
      state: wf.ok === true ? STATE.HEALTHY : STATE.DEGRADED,
      evidence: `last run ${wf.phase ?? "?"} at ${wf.lastRunAt ?? "?"} (status ${wf.status ?? "?"})`,
      source: "admin/status.json · workflowHealth", asOf: wf.lastRunAt ?? null, now,
      windowH: FRESHNESS_WINDOWS_H.workflow,
    }));

    const slate = adminStatus.slate ?? {};
    entries.push(entry({
      id: "slate-board", subject: `MLB board · ${slate.mlbSlate ?? "?"}`, department: "product-generation", sport: "mlb",
      state: (slate.mlbGames ?? 0) > 0 ? STATE.HEALTHY : STATE.NO_PLAY,
      evidence: `${slate.mlbGames ?? 0} games on the ${slate.mlbSlate ?? "?"} board`,
      source: "admin/status.json · slate", asOf: adminStatus.generatedAt ?? null, now,
      windowH: FRESHNESS_WINDOWS_H.adminStatus,
    }));

    // Paper products: awaiting lanes with zero active cards are a NO_PLAY, not degradation —
    // exactly the distinction the product-state contract introduced.
    const lanes = adminStatus.products?.bankBuilder?.lanes ?? [];
    const active = lanes.filter((l) => l.status === "active").length;
    entries.push(entry({
      id: "bank-builder", subject: "Bank Builder lanes", department: "products", sport: "mlb",
      state: active > 0 ? STATE.HEALTHY : STATE.NO_PLAY,
      evidence: active > 0 ? `${active} active lane(s)` : `0 active lanes — ${lanes.length} awaiting under unchanged policy`,
      source: "admin/status.json · products.bankBuilder", asOf: adminStatus.generatedAt ?? null, now,
      windowH: FRESHNESS_WINDOWS_H.adminStatus,
    }));

    entries.push(entry({
      id: "money-gate", subject: "Money coherence gate", department: "settlement-accounting", sport: null,
      state: adminStatus.moneyGate?.pass === true ? STATE.HEALTHY : STATE.INCIDENT,
      evidence: `crown−drawdown≡bankroll: ${adminStatus.moneyGate?.crownMinusDrawdownEqualsBankroll} · daily tracks canonical: ${adminStatus.moneyGate?.dailyTracksCanonical}`,
      source: "admin/status.json · moneyGate", asOf: adminStatus.generatedAt ?? null, now,
      windowH: FRESHNESS_WINDOWS_H.adminStatus, owner: "ENGINEERING",
    }));
  }

  // ── Internal alpha ─────────────────────────────────────────────────────────────────────────
  if (!alphaDay) {
    entries.push(entry({ id: "alpha-day", subject: "Internal alpha checkpoint", department: "launch", sport: null, state: STATE.UNKNOWN, evidence: "no alpha artifact", source: "ops/internal-alpha/latest.json", now, owner: "ENGINEERING" }));
  } else {
    entries.push(entry({
      id: "alpha-day", subject: `Internal alpha · day ${alphaDay.day}`, department: "launch", sport: null,
      state: alphaDay.verdict === "PASS" ? STATE.HEALTHY : alphaDay.verdict === "FAIL" ? STATE.INCIDENT : STATE.DEGRADED,
      evidence: `verdict ${alphaDay.verdict} · ${JSON.stringify(alphaDay.tally ?? {})} · sha ${alphaDay.sourceSha ?? "?"}`,
      source: "ops/internal-alpha/latest.json", asOf: `${alphaDay.observedEtDate}T23:59:59Z`, now,
      windowH: FRESHNESS_WINDOWS_H.alphaDay,
    }));
  }

  // ── Founder-owned launch gates: BLOCKED_EXTERNAL, never repository incidents ───────────────
  for (const g of gates) {
    if (g.owner !== "FOUNDER") continue;
    entries.push(entry({
      id: `gate:${g.id}`, subject: g.name, department: "launch", sport: null,
      state: g.status === "PASS" ? STATE.HEALTHY : STATE.BLOCKED_EXTERNAL,
      evidence: g.blocker ?? g.evidence, source: "launch-contract gates", asOf: null, now,
      owner: "FOUNDER",
      blocker: g.status === "PASS" ? null : g.blocker ?? "founder decision required",
    }));
  }

  // ── Sports: DERIVED from the twelve-stage gate, never hand-written (Release H/I). The maturity
  //    maps into ledger states: NOT_STARTED/SCAFFOLDED → PLANNED (absence is expected, work is
  //    known), SEASONAL_READY → OFF_SEASON, HISTORICAL_ONLY → OFF_SEASON, LIVE_ELIGIBLE for a
  //    non-live sport → BLOCKED_EXTERNAL on founder activation. MLB's live chain is covered by its
  //    own operational entries above, so it takes no sport row here.
  for (const [sport, a] of Object.entries(sportAssessments)) {
    if (sport === "mlb") continue;
    const maturity = deriveSportMaturity(a.stages, a);
    const gaps = remainingPath(a.stages);
    /*
     * P197: a SCAFFOLDED sport whose products AND publication stages are PROVEN is running a live
     * operating lane — daily receipts, public surfaces, scheduled settlement — and PLANNED
     * ("designed but not yet implemented") stopped being true for it the day those receipts
     * landed. HEALTHY here is a claim about the OPERATING CHAIN, never about the model: the
     * remaining gaps (typically model/calibration) stay named in the evidence string.
     */
    const operatingLive = a.stages.products?.status === "PROVEN" && a.stages.publication?.status === "PROVEN";
    entries.push(entry({
      id: `sport:${sport}`, subject: `${sport.toUpperCase()} · ${maturity}`, department: "multi-sport", sport,
      state: maturity === "LIVE_ELIGIBLE" ? STATE.BLOCKED_EXTERNAL
        : maturity === "SEASONAL_READY" || maturity === "HISTORICAL_ONLY" ? STATE.OFF_SEASON
        : operatingLive ? STATE.HEALTHY
        : STATE.PLANNED,
      evidence: `${GATE_STAGE_COUNT - gaps.length}/${GATE_STAGE_COUNT} gate stages proven · next: ${gaps[0]?.name ?? "founder activation"}`,
      source: "lib/sports/sport-gate assessments", asOf: null, now, owner: "ENGINEERING",
      blocker: gaps.find((g) => g.blocker)?.blocker ?? null,
    }));
  }

  const contradictions = detectContradictions({ adminStatus, alphaDay, boardDates, simDates, now });
  const all = [...contradictions, ...entries];

  const counts = {};
  for (const s of LEDGER_STATES) counts[s] = all.filter((e) => e.state === s).length;

  return {
    kind: "admin-evidence-ledger",
    schemaVersion: LEDGER_SCHEMA_VERSION,
    public: false,
    generatedFrom: { adminStatus: !!adminStatus, alphaDay: !!alphaDay, gates: gates.length, boardDates: boardDates.length, simDates: simDates.length },
    now,
    counts,
    // INCIDENT first, then UNKNOWN/STALE — the dashboard's first screen is what is wrong.
    entries: all.sort((a, b) => severityRank(a.state) - severityRank(b.state)),
    contradictionCount: contradictions.length,
  };
}

/** Sort severity: INCIDENT → UNKNOWN → STALE → DEGRADED → BLOCKED_EXTERNAL → rest. */
const SEVERITY_ORDER = ["INCIDENT", "UNKNOWN", "STALE", "DEGRADED", "BLOCKED_EXTERNAL", "NO_PLAY", "OFF_SEASON", "PLANNED", "HEALTHY", "N_A"];
export function severityRank(state) { const i = SEVERITY_ORDER.indexOf(state); return i === -1 ? SEVERITY_ORDER.length : i; }
