/**
 * Release history — shipped programs as auditable outcomes (Program 162 · Release C).
 *
 * The founder's rule: shipped work leaves the active lanes but must stay AUDITABLE. This register
 * is committed data — commit, date, departments advanced, outcome, defects found while shipping —
 * rendered verbatim on /launch and guard-bound so no entry here may still be an active card on the
 * work board (the pruning invariant, mechanical).
 *
 * HONESTY RULES: an entry exists only where the receipt (commit sha) is recorded. Programs 141-143
 * predate this register's records and are carried as a single UNRECORDED marker rather than
 * invented receipts. `rollbackParent` is the commit's first parent at ship time where recorded.
 */

export const RELEASE_HISTORY_VERSION = 1;

/** Newest first. Departments use the ten-department vocabulary rendered on /launch. */
export const RELEASE_HISTORY = Object.freeze([
  { program: "163", release: "D", commit: "faada98a6", date: "2026-08-12", departments: ["Sport Operations", "Settlement & records"], outcome: "FIRST JOINED UFC RESULTS: five real finals joined with committed lineage and graded, 12 pre-capture finals stayed quarantined, reconciliation exact; post-card lineage = valid no-change receipt (66 window-slides, zero replacements)", defectsFound: "the legitimate 83→17 window slide would have tripped tomorrow's mass-deletion rule — allowWindowSlide expectation added and pinned with tonight's real numbers; a count-era guard repointed to a floor", rollbackParent: "402da93f9" },
  { program: "163", release: "F", commit: "402da93f9", date: "2026-08-12", departments: ["Modeling & Research"], outcome: "per-event input-completeness classifier: every representative event REFUSES generation with exact reasons; NFL alone earns READY_EXCEPT_ODDS on its captured-injuries receipt", defectsFound: null, rollbackParent: "c31bc3808" },
  { program: "163", release: "E", commit: "c31bc3808", date: "2026-08-12", departments: ["Sport Operations", "Automation & Reliability"], outcome: "NFL corrections monitor (score-correction/status-regression/disappeared all review-gated) + first-join candidates discovered from artifacts (DET@CIN surfaces for Aug 13) + corrections runbook", defectsFound: null, rollbackParent: "af7815601" },
  { program: "163", release: "C", commit: "af7815601", date: "2026-08-11", departments: ["Automation & Reliability"], outcome: "cadence receipt verifier: pure per-sport evaluator with closed fail-closed verdicts, committed expectations for tomorrow, one-command invocation smoke-proven on yesterday's real run — nothing dispatched, nothing polls overnight", defectsFound: "the first NFL expectation said NO_RESULTS_YET — wrong, the trailing window still holds the quarantined Aug 7 final; corrected before shipping", rollbackParent: "1fb0fb79e" },
  { program: "163", release: "B", commit: "1fb0fb79e", date: "2026-08-11", departments: ["Data Integrity", "Modeling & Research"], outcome: "NBA lineups REJECTED with evidence (no free official pre-start source; box-score starters are POST_START by definition) + the fail-closed six-class lineup contract that any future licensed adapter must satisfy", defectsFound: null, rollbackParent: "ad984c04d" },
  { program: "163", release: "A", commit: "ad984c04d", date: "2026-08-11", departments: ["Automation & Reliability", "Engineering & Architecture"], outcome: "four stale P162 gate watchers stopped (targets mapped terminal first, zero orphan pollers verified) + the bounded single-target watcher whose poll loop structurally cannot repeat the unfulfillable-predicate leak + operating runbook", defectsFound: "root cause named: newest-run polling filtered by a superseded SHA can never match again; harness timeouts are not enforced on backgrounded loops", rollbackParent: "0e0cea42d" },
  { program: "162", release: "J", commit: "e65f5f834", date: "2026-08-11", departments: ["Sport Operations", "Settlement & records"], outcome: "UFC results operational: capture + bout-id adapter through the corpus-validated contract; first real run quarantined all 12 pre-capture finals for lineage with exact reconciliation — the third sport to prove the lineage rule live", defectsFound: "the /sports assurance spec expected 'completed games' and UFC honestly says 'bouts' — caught on all three engines, regex now noun-aware", rollbackParent: "0aa27ecb0" },
  { program: "162", release: "I", commit: "aeabffe19", date: "2026-08-11", departments: ["Settlement & records"], outcome: "UFC bout_winner settlement contract validated on all 1,716 corpus finals — the 25 DRAW_OR_NC bouts are exactly the quarantines (winner-only source refuses to split draw from NC); every sport now carries a corpus-validated grading spec", defectsFound: null, rollbackParent: "e4d1d1e20" },
  { program: "162", release: "H", commit: "8e8d3b566", date: "2026-08-11", departments: ["Data Integrity", "Automation & Reliability"], outcome: "injuries capture live: first committed captures normalized 800+77 live entries with zero quarantines (facts only, prose never stored); NFL matrix entry AVAILABLE on the receipt; NBA half-receipt recorded not stretched; cadence step wired", defectsFound: "the P156 shadow-gap guard hard-coded the gap count — honest movement broke it; now derived from shadowGaps()", rollbackParent: "8dccfe2b4" },
  { program: "162", release: "G", commit: "8dccfe2b4", date: "2026-08-11", departments: ["Data Integrity"], outcome: "injuries contract: URL-derived athlete identity with refusal, closed taxonomies, absence=UNKNOWN never healthy, staleness widens; real-sample fixtures from the live probe", defectsFound: null, rollbackParent: "6ade60159" },
  { program: "162", release: "F", commit: "6ade60159", date: "2026-08-11", departments: ["Modeling & Research"], outcome: "injuries source evaluation ACCEPTED with two named conditions (identity validation; absence is not health); matrix notes upgraded without flipping states", defectsFound: null, rollbackParent: "de9afefce" },
  { program: "162", release: "E", commit: "de9afefce", date: "2026-08-11", departments: ["Settlement & records", "Sport Operations"], outcome: "EPL results-path hardening (kickoff move, alias both-directions, score-bearing non-finals, memoryless corrections, duplicates) + corrections runbook with the ledger-writer acceptance condition", defectsFound: "the alias case's premise was wrong — Arsenal FC is a committed alias and joins; the test now proves both directions", rollbackParent: "f70bdea51" },
  { program: "162", release: "closeout", commit: "f3cad466c", date: "2026-08-11", departments: ["Admin & Roadmap"], outcome: "roadmap deduplicated against REALITY_GATED watches (one issue, one card); evidence regenerated at wall clock", defectsFound: "the closeout commit itself claimed history entries an aborted edit never applied — caught by re-reading the diff stat, fixed in this follow-up", rollbackParent: "63f321127" },
  { program: "162", release: "B", commit: "63f321127", date: "2026-08-11", departments: ["Product & UX"], outcome: "results paths discoverable on /sports (per-sport artifact-state lines); undated 'coming soon' promise replaced with the stated absence condition; three-engine proof extended", defectsFound: "a guard pinned the stale phrase — repointed to the invariant and the phrase is now banned", rollbackParent: "e5a6ed7bd" },
  { program: "162", release: "D", commit: "e5a6ed7bd", date: "2026-08-11", departments: ["Sport Operations", "Data Integrity"], outcome: "UFC forward-lineage classifier (stable-id joins, basis-recorded corners, closed taxonomy) reproducing the real fight-day addition from committed captures", defectsFound: null, rollbackParent: "e7d98314e" },
  { program: "162", release: "C", commit: "e7d98314e", date: "2026-08-11", departments: ["Admin & Roadmap"], outcome: "/launch command center: health strip, REALITY_GATED watches with countdowns, derived sprint lanes, auditable release history with the mechanical pruning invariant", defectsFound: null, rollbackParent: "5e1027533" },
  { program: "162", release: "A", commit: "5e1027533", date: "2026-08-11", departments: ["Sport Operations", "Data Integrity"], outcome: "NBA results vertical: tied-final quarantine contract validated on 4,179 corpus finals (zero pushes), keyless capture + id-join adapter, cadence-wired; honest NO_RESULTS_YET off-season first receipt", defectsFound: "none — first live capture returned the truthful empty window", rollbackParent: "48a5094c4" },
  { program: "161", release: "closeout", commit: "af03ef1b4", date: "2026-08-11", departments: ["Admin & Roadmap"], outcome: "evidence ledger refreshed with the Aug 11 board + production run (13 entries, 0 contradictions)", defectsFound: null, rollbackParent: "96f31a1f4" },
  { program: "161", release: "D", commit: "96f31a1f4", date: "2026-08-11", departments: ["Sport Operations", "Settlement & records"], outcome: "NFL results side: FINAL-only tie=PUSH contract validated on 1,001 corpus finals; capture + snapshot-union id-join adapter; cadence-wired", defectsFound: "first live final (CAR-ARI Aug 7) predated schedule capture — quarantined for missing lineage, proving the Sprint-045 rule live", rollbackParent: "3efb9a11d" },
  { program: "161", release: "C", commit: "38c2b2e78", date: "2026-08-11", departments: ["QA & Accessibility", "Engineering & Architecture"], outcome: "three-engine route/state assurance: 8-route contract on chromium/webkit/firefox in every quality-gate run, money-strip artifact parity, closed state vocabularies", defectsFound: "homepage featured-sim cards requested ESPN logos by full team name (~10 CDN 404s per visit, hidden by the monogram fallback) — fixed by threading teamAbbrs", rollbackParent: "81192df8f" },
  { program: "161", release: "B", commit: "81192df8f", date: "2026-08-11", departments: ["Automation & Reliability", "Data Integrity"], outcome: "cadence receipt #2 processed per sport (runs 31396780843 + 31500117960); morning window bounded as ONE documented exception across three guards", defectsFound: "daily-products stamps today ~2h before board generation — money legitimately leads the board by one day every morning; frozen test clocks rot with the cadence", rollbackParent: "778082d30" },
  { program: "161", release: "A", commit: "bcec50d3a", date: "2026-08-11", departments: ["Engineering & Architecture"], outcome: "Simulation Hub non-promotion proofs: 7 metamorphic guards + wiring bans close every accidental-promotion vector", defectsFound: null, rollbackParent: null },
  { program: "160", release: "A", commit: "703a26e2e", date: "2026-08-10", departments: ["Data Integrity", "Admin & Roadmap"], outcome: "product-truth contract: one owner per public figure, fail-closed reconciliation, bounded documented exceptions", defectsFound: "cross-lane auditors initially added to LANE_DIRS — the readers-allowlist is the correct repoint shape", rollbackParent: null },
  { program: "159", release: "A", commit: "49bcc7220", date: "2026-08-10", departments: ["Engineering & Architecture", "Admin & Roadmap"], outcome: "route assurance inventory: 50 routes reconciled across source, ownership table, and built export — zero findings", defectsFound: null, rollbackParent: null },
  { program: "158", release: "A", commit: "a6b517388", date: "2026-08-10", departments: ["Product & UX"], outcome: "/sports information architecture: one Sports·Schedules destination across command rail, nav strip, footer, homepage strip", defectsFound: "a NAV_ITEMS-only destination is invisible at desktop widths — desktop wayfinding is the command rail", rollbackParent: null },
  { program: "157", release: "A", commit: "ccf37e3e8", date: "2026-08-10", departments: ["Modeling & Research"], outcome: "shared four-sport model registry: derived index echoing committed evaluations verbatim, INCOMPLETE-honest, ranking vocabulary banned", defectsFound: null, rollbackParent: null },
  { program: "156", release: "B", commit: "7032fe644", date: "2026-08-10", departments: ["Admin & Roadmap"], outcome: "shadowGaps wired into the work board — odds merged to ONE founder card spanning four sports", defectsFound: null, rollbackParent: null },
  { program: "155", release: "C+D", commit: "adac8cca1", date: "2026-08-10", departments: ["Admin & Roadmap", "Modeling & Research"], outcome: "board filters (read-only) + pipeline lanes + shadow contract with per-sport live-input matrix", defectsFound: null, rollbackParent: null },
  { program: "154", release: "A", commit: "e23f855dd", date: "2026-08-10", departments: ["Sport Operations", "Settlement & records"], outcome: "EPL current-results path operational before opening day: honest PRESEASON states, canonical join, quarantine-total", defectsFound: null, rollbackParent: null },
  { program: "153", release: "A+E", commit: "af554cbba", date: "2026-08-10", departments: ["Modeling & Research", "Admin & Roadmap"], outcome: "UFC research vertical (abstaining Elo, coverage 25.6% by design) + the /launch work board", defectsFound: "ESPN MMA endpoint rate-limits bursts — resumable fetcher with 15s spacing", rollbackParent: null },
  { program: "152", release: "A", commit: "4c2dbb032", date: "2026-08-10", departments: ["Modeling & Research", "Automation & Reliability"], outcome: "NBA research vertical (4,179 finals; leap-day + All-Star + Cup-final traps caught by exact-count refusals) + cadence receipt #1", defectsFound: "ESPN monthly windows miss leap days; season.year labels the end year", rollbackParent: null },
  { program: "151", release: "A+B", commit: "ed9e913df", date: "2026-08-10", departments: ["Modeling & Research", "Settlement & records"], outcome: "NFL research vertical (1,001 finals, 7 ties preserved) + EPL settlement validated on a full real season", defectsFound: "Pro Bowl AFC/NFC rows caught by the 32-team refusal", rollbackParent: null },
  { program: "150", release: "A", commit: "55fa6eb4c", date: "2026-08-09", departments: ["Sport Operations"], outcome: "NBA + UFC forward coverage live on /sports; four-sport daily cadence workflow", defectsFound: null, rollbackParent: null },
  { program: "149", release: "R1-R3", commit: "3d5cd6f8", date: "2026-08-09", departments: ["Modeling & Research", "Sport Operations"], outcome: "shared replay harness + strict artifact modes; EPL 380/380 capture with dual-source membership verification", defectsFound: "community source named two promoted clubs outside the committed alias table — quarantined, never auto-minted", rollbackParent: null },
  { program: "148", release: "B-D", commit: "118a1701d", date: "2026-08-09", departments: ["Product & UX", "Sport Operations"], outcome: "/sports revived as the four-sport schedule directory; NFL first real capture; EPL research corpus + baselines", defectsFound: null, rollbackParent: null },
  { program: "144-147", release: "A-I", commit: "281de088", date: "2026-08-08", departments: ["Engineering & Architecture", "Admin & Roadmap", "Product & UX"], outcome: "ledger v2, identity ratchet, provable-only Build compat, hour-aware labels, 12-stage sport gate (MLB sole LIVE_ELIGIBLE)", defectsFound: null, rollbackParent: null },
  { program: "141-143", release: "—", commit: null, date: "2026-08-07", departments: ["Engineering & Architecture"], outcome: "UNRECORDED in this register: these programs predate the release-history data structure; their receipts live in the program reports, not here — never invented retroactively", defectsFound: null, rollbackParent: null },
]);
