/**
 * Release history — shipped programs as auditable outcomes (Program 162 · Release C).
 *
 * The founder's rule: shipped work leaves the active lanes but must stay AUDITABLE. This register
 * is committed data — commit, date, departments advanced, outcome, defects found while shipping —
 * rendered verbatim on /launch and guard-bound so no entry here may still be an active card on the
 * work board (the pruning invariant, mechanical).
 *
 * HONESTY RULES: an entry exists only where the receipt (commit sha) is recorded. Programs 141-143
 * predate this register's records and are carried as a single UNRECORDED marker rather than
 * invented receipts. `rollbackParent` is the commit's first parent at ship time where recorded.
 */

export const RELEASE_HISTORY_VERSION = 1;

/** Newest first. Departments use the ten-department vocabulary rendered on /launch. */
export const RELEASE_HISTORY = Object.freeze([
  { program: "207", release: "R-A", commit: "29d682270", date: "2026-08-25", departments: ["Operations & Reliability", "Product & UX"], outcome: "overnight receipts verified (Aug-24 settled 1-14 honestly); Bank Builder trio tokenized (98 literals, ratchet locked 1,268→1,170); the 8.1MB /results fixed at its render owner (cap-3 + 79 linked date archives, −65%) with a page-weight budget guard", defectsFound: null, rollbackParent: "ec0689510" },
  { program: "206", release: "R-K", commit: "785a8e8bc", date: "2026-08-25", departments: ["Operations & Reliability"], outcome: "final assurance — engineering-complete on all three sports; e2e matrix grown to 413/0/6 with the 28-check controls/assets spec; the filter-restore test restated day-phase-proof", defectsFound: null, rollbackParent: "af2e39fbd" },
  { program: "206", release: "R-A", commit: "cc9a1937a", date: "2026-08-25", departments: ["Release engineering"], outcome: "activation-gap truth (every non-proven stage instrument-built and bar-frozen — REALITY/FOUNDER only) + full controls/assets inspection + the conservation window restated to the nightly's real cadence", defectsFound: "the window fix hit the Intl midnight-hour-24 trap — third repo occurrence; hourCycle h23", rollbackParent: "244d56389" },
  { program: "205", release: "R-A", commit: "244d56389", date: "2026-08-25", departments: ["Release engineering"], outcome: "the exact bytes users download — the wrong boundary found, proven, and closed (verified PDF embedded behind the downloads capability; content-addressed console copy; structural row verifier v2 with twelve failing fixtures)", defectsFound: "the stricter machinery caught a null-null register row, five space-bearing ids the old regex missed, a stale-receipt package refusal, and its own ban-string inside a new register row", rollbackParent: "66e5d7acf" },
  { program: "204", release: "R-H", commit: "71c86c7aa", date: "2026-08-24", departments: ["Operations & Reliability"], outcome: "operator onboarding — the current loop on one page (cadence table with per-workflow receipts); the retired June-era manual loop labelled so a new operator cannot run dead commands", defectsFound: null, rollbackParent: "ad3795681" },
  { program: "204", release: "R-A", commit: "ad3795681", date: "2026-08-24", departments: ["Release engineering"], outcome: "final-file truth — the founder's PDF was right: object-coercion queue text and empty posture cards fixed at the view-model; final-output verifier renders and parses the actual PDF, writes the checksum receipt /launch renders; eight corruption fixtures proven to fail", defectsFound: "the in-flight conservation rule broke when a bot commit took HEAD — restated to newest-convention-commit", rollbackParent: "f298e26cb" },
  { program: "203", release: "R-K", commit: "9f0247a71", date: "2026-08-24", departments: ["Operations & Reliability"], outcome: "final assurance — the daily loop proven live (two MLB cycles conserve; UFC population-exact 12=12; NFL typed refusals), everything regenerated at the close stamp; production converged on the exact tip", defectsFound: "the bout-set diff refuted my own P202 scratch claim — the 13-to-12 read was the pre-rebuild artifact shape, corrected in this commit", rollbackParent: "f494d06db" },
  { program: "203", release: "R-B", commit: "f494d06db", date: "2026-08-24", departments: ["Sport Operations"], outcome: "EPL pair four closes live — Fulham 2-3 Chelsea graded end to end through the deployed owners (match HIT p=0.381; 62 player rows graded, 18 void; paired learning 4/30, market ahead, SAMPLE_TOO_SMALL stated)", defectsFound: null, rollbackParent: "35d9c21a3" },
  { program: "203", release: "R-A", commit: "35d9c21a3", date: "2026-08-24", departments: ["Release engineering"], outcome: "the operating record becomes a generated, conserved, self-validating artifact", defectsFound: "its own validator caught the legacy/new register blocks interleaving out of date order, and the schema guard caught empty departments + a misplaced closure row before commit", rollbackParent: "89ccc8680" },
  /*
   * PROGRAM 198 CLOSURE RECEIPT (appended by P199 Phase 0). The one COMPLETE criterion left open
   * at the P198 report cut — exact-tip production convergence — is now proven: production serves
   * 01464f3cb, a covering SHA whose ancestry includes the P198 tip dc52ebca1 (git merge-base
   * --is-ancestor, verified 2026-08-24 13:36 UTC), the build stamped 13:10 UTC, and the first
   * unattended night ran the P198 code end to end (nightly settle 08:12 UTC, UFC post-card
   * quiet-exit with reconciliation intact, auto-refresh). Program 198 reclassifies COMPLETE:
   * ENGINEERING_READY zero by conservation, every remaining item reality- or founder-gated with
   * acceptance tests, tiers generated, assurance green.
   */
  { program: "198", release: "closure", commit: "01464f3cb", date: "2026-08-24", departments: ["Operations & Reliability"], outcome: "P198 reclassified COMPLETE on production convergence: covering SHA ancestry-proven over dc52ebca1; queue-zero live; first unattended night green (nightly settle, UFC post-card quiet exit, cadence receipts)", defectsFound: "the overnight receipts exposed a loop-scoped missing-count overwriting the cumulative MLB game record (fixed: derived from the linescore cache every write) and the predicted 08-23 snapshot seam day (closed: +45 rows from local history)", rollbackParent: "dc52ebca1" },

  /*
   * CONVENTION-ERA ROWS (P203 Release A). Derived mechanically from git by
   * scripts/ops/append-release-history.mjs — outcome text is each release commit's own subject
   * line, rollbackParent its first parent. The guard test re-derives the same set from git, so a
   * release commit missing from this register fails the build: the operating record renders FROM
   * this owner and can no longer silently truncate. Newest first, like the rest of the file.
   */
  { program: "202", release: "R-L", commit: "c31b035af", date: "2026-08-24", departments: ["Release engineering"], outcome: "final assurance — everything regenerated at one stamp (21:20Z)", defectsFound: null, rollbackParent: "a35783aa6" },
  { program: "202", release: "R-F", commit: "c99a8dace", date: "2026-08-24", departments: ["Release engineering"], outcome: "three-engine × four-width matrix — and it caught two real defects", defectsFound: null, rollbackParent: "1cbe25a94" },
  { program: "202", release: "R-E", commit: "1cbe25a94", date: "2026-08-24", departments: ["Release engineering"], outcome: "signature-product audit — eleven lanes, every one typed", defectsFound: null, rollbackParent: "76c6fed2a" },
  { program: "202", release: "R-D", commit: "c92770ec6", date: "2026-08-24", departments: ["Release engineering"], outcome: "claims contract — the guard suite over the existing three-layer pattern", defectsFound: null, rollbackParent: "884917729" },
  { program: "202", release: "R-C fix", commit: "884917729", date: "2026-08-24", departments: ["Release engineering"], outcome: "chip border tokenized — the colour ratchet was right", defectsFound: null, rollbackParent: "fe37312d8" },
  { program: "202", release: "R-C", commit: "4e5b69728", date: "2026-08-24", departments: ["Release engineering"], outcome: "picks-board filter chips — selection over the one ranking, state in the URL", defectsFound: null, rollbackParent: "7e118391e" },
  { program: "202", release: "R-B", commit: "7e118391e", date: "2026-08-24", departments: ["Release engineering"], outcome: "qualified-leg adoption on Build + Market Center — and the guards caught six real claims", defectsFound: null, rollbackParent: "0fe202399" },
  { program: "202", release: "R-A", commit: "0fe202399", date: "2026-08-24", departments: ["Release engineering"], outcome: "product-day full adoption — the homepage stops rediscovering truth", defectsFound: null, rollbackParent: "1ed07208c" },
  { program: "202", release: "Phase 0", commit: "1ed07208c", date: "2026-08-24", departments: ["Release engineering"], outcome: "baseline reconciled + a real P0 caught and fixed at its owner", defectsFound: null, rollbackParent: "dd3590c84" },
  { program: "201", release: "L", commit: "763a7ea29", date: "2026-08-24", departments: ["Release engineering"], outcome: "final assurance regeneration at one stamp (2026-08-24T19:55Z)", defectsFound: null, rollbackParent: "60727b521" },
  { program: "201", release: "R-F", commit: "60727b521", date: "2026-08-24", departments: ["Release engineering"], outcome: "lab conservation proven — one real orphan found, adjudicated by name", defectsFound: null, rollbackParent: "66bd99983" },
  { program: "201", release: "R-E", commit: "5a9b21d15", date: "2026-08-24", departments: ["Release engineering"], outcome: "per-sport Top 10 on /today, from the one ranked owner", defectsFound: null, rollbackParent: "76634222d" },
  { program: "201", release: "R-D", commit: "76634222d", date: "2026-08-24", departments: ["Release engineering"], outcome: "mobile bar = the six primary destinations (charter F1)", defectsFound: null, rollbackParent: "2e9174afb" },
  { program: "201", release: "R-C", commit: "2e9174afb", date: "2026-08-24", departments: ["Release engineering"], outcome: "Suggested Parlays destination completed — NFL lane page + every lane reachable from /build", defectsFound: null, rollbackParent: "1e39711f8" },
  { program: "201", release: "R-B", commit: "1e39711f8", date: "2026-08-24", departments: ["Release engineering"], outcome: "NFL lane closed by machinery — grader, ladder, one shared band engine", defectsFound: null, rollbackParent: "19f64d7ec" },
  { program: "201", release: "R-A", commit: "19f64d7ec", date: "2026-08-24", departments: ["Release engineering"], outcome: "product-day authority + qualified-leg contract + versioned risk rubric", defectsFound: null, rollbackParent: "c42ec5d46" },
  { program: "201", release: "Phase 0", commit: "69948157a", date: "2026-08-24", departments: ["Release engineering"], outcome: "operating record reconciled + derived artifacts at one stamp", defectsFound: null, rollbackParent: "58008bd2f" },
  { program: "200", release: "R-F", commit: "c8be5fe64", date: "2026-08-24", departments: ["Release engineering"], outcome: "coverage builder learns the multi lane's tier-grid dialect", defectsFound: null, rollbackParent: "3fef40d8d" },
  { program: "200", release: "R-E", commit: "33bacf4ee", date: "2026-08-24", departments: ["Release engineering"], outcome: "/today carries the daily parlay evaluations + retired-link fix", defectsFound: null, rollbackParent: "48b74abb3" },
  { program: "200", release: "R-D", commit: "48b74abb3", date: "2026-08-24", departments: ["Release engineering"], outcome: "primary nav trimmed to six destinations + Results record directory", defectsFound: null, rollbackParent: "cc2d6a439" },
  { program: "200", release: "R-C", commit: "5b9960b38", date: "2026-08-24", departments: ["Release engineering"], outcome: "per-risk-tier Lab record + EPL stale-claim fix", defectsFound: null, rollbackParent: "8d8b3be36" },
  { program: "200", release: "R-B", commit: "8d8b3be36", date: "2026-08-24", departments: ["Release engineering"], outcome: "homepage journey reset — three front-door actions, four-sport hub, suggested-parlays preview", defectsFound: null, rollbackParent: "77d287f2c" },
  { program: "200", release: "R-A", commit: "9fcf78b5e", date: "2026-08-24", departments: ["Release engineering"], outcome: "parlay truth spine — lab eligibility truth fixes, risk-coverage matrix v2, relic guards restated", defectsFound: null, rollbackParent: "27a4a3c22" },
  { program: "199", release: "H", commit: "bba7f9c1e", date: "2026-08-24", departments: ["Release engineering"], outcome: "assurance: P199 final regeneration — conservation exact, receipts current (Release H)", defectsFound: null, rollbackParent: "300e870da" },
  { program: "199", release: "D", commit: "300e870da", date: "2026-08-24", departments: ["Release engineering"], outcome: "founder: five gate decisions, answerable in one sitting (P199 Release D)", defectsFound: null, rollbackParent: "f6d394d38" },
  { program: "199", release: "A", commit: "e05ea922b", date: "2026-08-24", departments: ["Release engineering"], outcome: "ufc: fight-week control — lineage on a cadence, the Aug-29 watch armed (P199 Release A)", defectsFound: null, rollbackParent: "310ad2ad3" },
  { program: "198", release: "G", commit: "dc52ebca1", date: "2026-08-24", departments: ["Release engineering"], outcome: "assurance: final regeneration at the P198 tip — inventory reconciled, a11y structural clean (Release G)", defectsFound: null, rollbackParent: "58d5fbad2" },
  { program: "198", release: "D+F", commit: "58d5fbad2", date: "2026-08-24", departments: ["Release engineering"], outcome: "ops+tiers: one executable operating system; the activation tiers are pinned as generated (P198 Releases D+F)", defectsFound: null, rollbackParent: "5140a3d37" },
  { program: "198", release: "A", commit: "5140a3d37", date: "2026-08-23", departments: ["Release engineering"], outcome: "nba: the engineering queue reaches ZERO — every remaining gap names its gate (P198 Release A)", defectsFound: null, rollbackParent: "cf8a5acc2" },
  { program: "197", release: "E", commit: "cf8a5acc2", date: "2026-08-23", departments: ["Release engineering"], outcome: "nba: first-event-ready foundation — verify what can be verified, gate what cannot (P197 Release E)", defectsFound: null, rollbackParent: "0531593b5" },
  { program: "197", release: "C+D", commit: "0531593b5", date: "2026-08-23", departments: ["Release engineering"], outcome: "nfl+ux: regular-season readiness with frozen bars; the three-engine matrix runs green (P197 Releases C+D)", defectsFound: null, rollbackParent: "28a249dd3" },
  { program: "197", release: "B", commit: "93813a826", date: "2026-08-23", departments: ["Release engineering"], outcome: "epl: five stages proven by receipts that already existed — 11/12 (P197 Release B)", defectsFound: null, rollbackParent: "058f76ea2" },
  { program: "197", release: "A", commit: "058f76ea2", date: "2026-08-23", departments: ["Release engineering"], outcome: "ufc: seven stages proven by receipts — the operating loop closes (P197 Release A)", defectsFound: null, rollbackParent: "33ebc0699" },
  { program: "196", release: "J", commit: "33ebc0699", date: "2026-08-23", departments: ["Release engineering"], outcome: "launch: roadmap reset to current truth; final P196 assurance regeneration (Release J)", defectsFound: null, rollbackParent: "2eebec892" },
  { program: "196", release: "F", commit: "607828d45", date: "2026-08-23", departments: ["Release engineering"], outcome: "nba: a healthy quiet lane can now prove it ran — the schedule cadence receipt (P196 Release F)", defectsFound: null, rollbackParent: "9d0becd95" },
  { program: "196", release: "E", commit: "9d0becd95", date: "2026-08-23", departments: ["Release engineering"], outcome: "nfl: season cohorts before the season can blend them (P196 Release E)", defectsFound: null, rollbackParent: "f8271a6f3" },
  { program: "196", release: "D", commit: "f8271a6f3", date: "2026-08-23", departments: ["Release engineering"], outcome: "epl: the learning artifact becomes the only live calibration-count authority (P196 Release D)", defectsFound: null, rollbackParent: "080f3649b" },
  { program: "196", release: "C", commit: "72d5a7d5c", date: "2026-08-23", departments: ["Release engineering"], outcome: "ufc: the 08-22 main card was ungradeable by construction — fixed, graded, and one record region (P196 Release C)", defectsFound: null, rollbackParent: "1e652ae02" },
  { program: "196", release: "B", commit: "1e652ae02", date: "2026-08-23", departments: ["Release engineering"], outcome: "mlb: game-level predictions enter the public record; one owner for the risk-substitute rule (P196 Release B)", defectsFound: null, rollbackParent: "6e0f9f0b6" },
  { program: "196", release: "A", commit: "a06dfa1cf", date: "2026-08-23", departments: ["Release engineering"], outcome: "launch: sport closure packets — the completion control plane (P196 Release A)", defectsFound: null, rollbackParent: "e2639ad2e" },
  { program: "184", release: "Phase-0+A", commit: "eeff42d61", date: "2026-08-18", departments: ["Release engineering"], outcome: "the measured UI/UX baseline, and a ratchet on the drift", defectsFound: null, rollbackParent: "8cf568d96" },
  { program: "178", release: "Phase 0", commit: "d12bde0c2", date: "2026-08-14", departments: ["Release engineering"], outcome: "withdraw P177's false-closure headline and guard against the next one", defectsFound: null, rollbackParent: "7fea587d9" },
  { program: "176", release: "Phase 0", commit: "fecbcbe74", date: "2026-08-13", departments: ["Release engineering"], outcome: "the kickoff lock and post-start refusal PROVEN against real elapsed time", defectsFound: null, rollbackParent: "6a49c684a" },

  { program: "169", release: "J+K", commit: "fcedebc1b", date: "2026-08-13", departments: ["Product & UX", "Sport Operations"], outcome: "public /nfl honesty hub: real slate + finals from committed captures, market-by-market coverage table with typed states; route inventory 51/0 findings; boundary guards repointed to rendered-text rules (the /sports-revival pattern); NFL event-day runbook (T-24h through corrections)", defectsFound: "the sport-hub redirect-only rule and nav allowlist fired on the new route — adjudicated as the founder-charter graduation with the invariant preserved in rendered text", rollbackParent: "0f3010e06" },
  { program: "169", release: "G", commit: "0f3010e06", date: "2026-08-13", departments: ["Product & UX", "Modeling & Research"], outcome: "Endzone Vault: five modes, correlation-aware compatibility (same-game CORRELATION_NOT_VALIDATED without a joint receipt; cross-game independence disclosed), separate append-only paper ledger with first real NO_PLAY entry naming its three true blockers", defectsFound: null, rollbackParent: "664f0dd84" },
  { program: "169", release: "F", commit: "664f0dd84", date: "2026-08-13", departments: ["Modeling & Research"], outcome: "anytime-TD engine: team-first Poisson allocation refusing without a committed points-to-TD calibration receipt; mandatory residual; passer/receiver one-event rule; four publication gates (modelled-yet-unpublishable is real); settlement credit rules (scoring player wins, passer-only loses, DNP voids)", defectsFound: "float residue at share-0 clamped by its own test", rollbackParent: "b06027f80" },
  { program: "169", release: "D", commit: "b06027f80", date: "2026-08-13", departments: ["Sport Operations", "Modeling & Research"], outcome: "participation contract: closed typed set, absence-of-injury-data never health, preseason snap-scenario gate (real DET@CIN pools: >40 ROLE_UNCERTAIN per side, zero unevidenced actives), reviewed expiring overrides, allocation coherence refusals", defectsFound: null, rollbackParent: "6c7dc70b3" },
  { program: "169", release: "C", commit: "6c7dc70b3", date: "2026-08-13", departments: ["Modeling & Research"], outcome: "joint team-score simulation: deterministic seeded stream, legal scoring support, measured convergence; REPORTED win head = replay-validated elo-logistic with the margin-probit divergence as a visible diagnostic; preseason shrink FIT on 23-24 (0.2) with 2025 test at ~coin, stated; score MAE 7.584 beats naive 7.941, 80pct coverage 0.8015", defectsFound: "its own eval caught the two-heads divergence (9.6pp) before anything shipped", rollbackParent: "0cf89b8e2" },
  { program: "169", release: "A", commit: "0cf89b8e2", date: "2026-08-13", departments: ["Sport Operations", "Platform"], outcome: "NFL source+identity foundation: registry roles incl. an explicitly UNSOURCED weather role, canonical player registry keyed by durable ids (first real capture 32/32 teams, 2,991 athletes, 0 quarantined), provider-data season typing, per-input freshness matrix", defectsFound: null, rollbackParent: "97fbb4e49" },
  { program: "167", release: "H", commit: "1a294d9c8", date: "2026-08-12", departments: ["Modeling & Research", "Platform"], outcome: "all-sport prediction factory: adapter manifests, closed output-variant validators proven on the real engines, ONE readiness registry (six independent axes, receipts/reasons, cross-sport ranking banned in data and code) rendered verbatim on /launch; MLB described never wrapped; NBA compatibility proven at variant level without a fake model", defectsFound: null, rollbackParent: "977f432af" },
  { program: "167", release: "G", commit: "977f432af", date: "2026-08-12", departments: ["Modeling & Research", "Sport Operations"], outcome: "EPL engine: committed poisson baseline promoted with EXACT replay parity (n=1140, logLoss 1.0017), draw ECE 0.0262, RPS/totals diagnostics, deferred-alternatives stopping rule, lineups NOT_REQUIRED_FOR_TEAM_V1; shadow ladder proves all 10 opening fixtures READY_EXCEPT_ODDS (2 promoted clubs cold-start via verified list)", defectsFound: null, rollbackParent: "9b8aa29d3" },
  { program: "167", release: "F", commit: "9b8aa29d3", date: "2026-08-12", departments: ["Modeling & Research", "Sport Operations"], outcome: "UFC winner engine: abstaining Elo promoted (coverage semantics preserved 25.4%, logLoss 0.6788, ECE 0.0157), identity by unique normalized name (ambiguity abstains), CARD_UNCERTAIN lineage gate (weigh-ins MISSING stated); REAL UFC 330 preflight committed: 11 READY_EXCEPT_ODDS + 1 ABSTAIN(SPARSE); weekend runbook gains shadow/market preflight steps", defectsFound: null, rollbackParent: "e1e8c50f3" },
  { program: "167", release: "E", commit: "e1e8c50f3", date: "2026-08-12", departments: ["Modeling & Research"], outcome: "NFL v1 engine: analytical margin/total heads over the cutoff Elo (train 2023-24, held-out 2025: logLoss 0.6478 vs coin 0.6931, ECE 0.0446), preseason ABSTAINS by model card, shadow ladder live in tests over the real next event (DET@CIN abstains preseason, zero probability leakage)", defectsFound: "validateShadowRun demands provenance — caught by its own validator on first CURRENT emission", rollbackParent: "fdc1d43ae" },
  { program: "167", release: "D", commit: "fdc1d43ae", date: "2026-08-12", departments: ["Sport Operations", "Automation & Reliability"], outcome: "NFL first-result verification: the lineage gate fired LIVE on the first real final (CAR@ARI quarantined — no pre-event schedule capture exists; backfill forbidden), reconciliation exact, pinned as permanent real-data test + receipt doc; watch sharpened to when the cadence can land evidence (14:15Z); OT/tie join pins added", defectsFound: null, rollbackParent: "94710831a" },
  { program: "167", release: "C", commit: "94710831a", date: "2026-08-12", departments: ["Market Intelligence", "Platform"], outcome: "odds evidence lane: per-sport market scope (UFC h2h-only, EPL three-way + totals, NFL h2h/spreads/totals), three-way no-vig preserving the draw, pointed two-way same-point rule, provider→canonical joins with lineage (SWAPPED reported never flipped), seven-state availability classifier with the exact AUTHORIZATION_REQUIRED line on /launch; local canary refusal verified, zero credit calls", defectsFound: null, rollbackParent: "72be98187" },
  { program: "167", release: "B", commit: "72be98187", date: "2026-08-12", departments: ["Admin & Roadmap", "Product & UX"], outcome: "/launch became an operator product: IA v2 (12 groups, task-first + Onboarding), persistent left nav + mobile strip + env/commit top bar, five-phase daily loop (Observe→Verify→Build→Release→Close) derived purely from the board with exactly-once placement, top-3 actions, URL-state deep-link filters, per-sport stage receipts in words, protected-money tile, sanitized onboarding guide; verified in-browser at 390/768/1440", defectsFound: null, rollbackParent: "8a290c5cd" },
  { program: "167", release: "A", commit: "8a290c5cd", date: "2026-08-12", departments: ["Admin & Roadmap", "Security & Privacy"], outcome: "protected operator deployment LIVE: separate gtp-ops project (internal build) behind Vercel Authentication; production domain removed after a ~4-minute unauthenticated window (incident + never-re-add rule recorded); verify-admin-access 4/4; Dhruv access PENDING_IDENTITY (host plan gate)", defectsFound: "Standard Protection excludes auto-assigned production domains — discovered by probing, contained by domain deletion; the paid all-deployments tier was refused by program boundary", rollbackParent: "7101a0c99" },
  { program: "166", release: "E", commit: "1a44eb9dc", date: "2026-08-12", departments: ["Sport Operations", "Modeling & Research"], outcome: "NFL deep slice: baseline Elo promoted to a leakage-proof cutoff-versioned strength state (params identical, target-game exclusion structural) + real-event assembly proving READY_EXCEPT_ODDS on the next scheduled game from committed artifacts", defectsFound: null, rollbackParent: "ce17d09aa" },
  { program: "166", release: "A+B", commit: "ce17d09aa", date: "2026-08-12", departments: ["Admin & Roadmap", "Product & UX"], outcome: "operator console IA: eleven-group contract with drift-proof sticky nav, env badge + as-of clock, Runbooks index, and the Dhruv transition-readiness section (documentation only — no transfer occurred or authorized)", defectsFound: null, rollbackParent: "7d5714eb9" },
  { program: "165", release: "I", commit: "487f467b8", date: "2026-08-12", departments: ["Automation & Reliability"], outcome: "first fully-verified scheduled cadence: run 31605451090, ten classes, zero failures, first scheduled injuries receipts", defectsFound: "the countdown fixture clock rotted when the watch moved — advanced with the watch", rollbackParent: "addf382a8" },
  { program: "165", release: "J", commit: "6f7a9af4d", date: "2026-08-12", departments: ["Admin & Roadmap"], outcome: "one authority per blocker: five founder roadmap duplicates pruned into the registry; stale shipped NOW item removed; horizons refilled with the post-answer ENGINEERING sequence; the board's odds card is an explicit pointer", defectsFound: "the horizon guard rightly refused empty lanes — filled with execution items, not decision duplicates", rollbackParent: "25141eb44" },
  { program: "165", release: "A-addendum", commit: "8ba0e6a3b", date: "2026-08-12", departments: ["Admin & Roadmap"], outcome: "the Founder Action Sheet renders each blocker's exact answer tokens (recommended first) + the form pointer — answerable from one screen", defectsFound: null, rollbackParent: "8d74c5ad3" },
  { program: "165", release: "A/B/D/H", commit: "8d74c5ad3", date: "2026-08-12", departments: ["Admin & Roadmap", "Launch & External Gates"], outcome: "Founder Response Form (enumerated non-secret choices; PII/secret/stale-version refusal; transitions structurally unable to CLOSE) + read-only orchestrator proven on the template; legal approvals now require the exact reviewed content hash; analytics collector deployment spec; read-only admin-access verifier", defectsFound: "the stronger legal hash rule reached the beta prerequisite fixture — fixture followed the rule, the guard kept its teeth", rollbackParent: "14b31c880" },
  { program: "164", release: "R6+R7", commit: "e9a6e2740", date: "2026-08-12", departments: ["Launch & External Gates", "Performance & Security"], outcome: "beta access (PII structurally refused, deny-by-default, prerequisite gate wired to the real legal manifest) + admin-access ADR and deny-by-default contract; all seven shared blockers ENGINEERING_READY_FOR_FOUNDER", defectsFound: null, rollbackParent: "80bb3a66a" },
  { program: "164", release: "R5", commit: "80bb3a66a", date: "2026-08-12", departments: ["Launch & External Gates"], outcome: "legal section-3 packet (11 numbered items, FOR REVIEW) + publish guard: unapproved text structurally unshippable; approval = named reviewer + role + date + packet version", defectsFound: null, rollbackParent: "8ae72c202" },
  { program: "164", release: "R2", commit: "9fe54d536", date: "2026-08-12", departments: ["Data Integrity", "Performance & Security"], outcome: "odds engineering complete: provider-neutral contract with visible-vig no-vig, fail-closed secret shapes, four-sport fixtures, authorization-gated canary (dry-run default, ceiling+floor, redacted, self-leak-scanned; refusals proven as real subprocesses)", defectsFound: "a structural pin matched the docstring's mention of the refused form — repointed to the executable property", rollbackParent: "e8b20f1c6" },
  { program: "164", release: "R1", commit: "e8b20f1c6", date: "2026-08-12", departments: ["Admin & Roadmap", "Launch & External Gates"], outcome: "shared-blocker registry (seven blockers, once each, closed states, secrets discipline guard-enforced) + the dependency-ordered Founder Action Sheet on /launch", defectsFound: null, rollbackParent: "9996492a1" },
  { program: "163", release: "J", commit: "2dc1778fd", date: "2026-08-12", departments: ["Engineering & Architecture", "Sport Operations"], outcome: "EPL corrections monitor ready before opening day + the n=3 results-monitor core consolidation; NFL/UFC tests passed untouched on the wrappers (behavioral identity by test)", defectsFound: "one core evidence string drifted from the pinned phrasing — the tests won, not the rewrite", rollbackParent: "a8113cc99" },
  { program: "163", release: "I", commit: "a8113cc99", date: "2026-08-12", departments: ["Sport Operations"], outcome: "UFC corrections monitor: OVERTURNED_RESULT and DECISION_CHANGE review-gated; tonight's five finals read as exactly five BECAME_FINAL from the committed capture, zero invented overturns", defectsFound: null, rollbackParent: "5d4e37dab" },
  { program: "163", release: "G+H", commit: "3db8a1d4a", date: "2026-08-12", departments: ["Admin & Roadmap", "Performance & Security"], outcome: "Today queue on /launch; OVERDUE watch state (a missed observation cannot rot as merely DUE); route payload measurements recorded (/results 8.5MB flagged as its own follow-up card); secret scan clean; /sports honesty re-verified with the new UFC artifact", defectsFound: "the /results static HTML weighs 8.5MB — measured, flagged, deliberately NOT hacked at overnight", rollbackParent: "2263b2f39" },
  { program: "163", release: "D", commit: "faada98a6", date: "2026-08-12", departments: ["Sport Operations", "Settlement & records"], outcome: "FIRST JOINED UFC RESULTS: five real finals joined with committed lineage and graded, 12 pre-capture finals stayed quarantined, reconciliation exact; post-card lineage = valid no-change receipt (66 window-slides, zero replacements)", defectsFound: "the legitimate 83→17 window slide would have tripped tomorrow's mass-deletion rule — allowWindowSlide expectation added and pinned with tonight's real numbers; a count-era guard repointed to a floor", rollbackParent: "402da93f9" },
  { program: "163", release: "F", commit: "402da93f9", date: "2026-08-12", departments: ["Modeling & Research"], outcome: "per-event input-completeness classifier: every representative event REFUSES generation with exact reasons; NFL alone earns READY_EXCEPT_ODDS on its captured-injuries receipt", defectsFound: null, rollbackParent: "c31bc3808" },
  { program: "163", release: "E", commit: "c31bc3808", date: "2026-08-12", departments: ["Sport Operations", "Automation & Reliability"], outcome: "NFL corrections monitor (score-correction/status-regression/disappeared all review-gated) + first-join candidates discovered from artifacts (DET@CIN surfaces for Aug 13) + corrections runbook", defectsFound: null, rollbackParent: "af7815601" },
  { program: "163", release: "C", commit: "af7815601", date: "2026-08-11", departments: ["Automation & Reliability"], outcome: "cadence receipt verifier: pure per-sport evaluator with closed fail-closed verdicts, committed expectations for tomorrow, one-command invocation smoke-proven on yesterday's real run — nothing dispatched, nothing polls overnight", defectsFound: "the first NFL expectation said NO_RESULTS_YET — wrong, the trailing window still holds the quarantined Aug 7 final; corrected before shipping", rollbackParent: "1fb0fb79e" },
  { program: "163", release: "B", commit: "1fb0fb79e", date: "2026-08-11", departments: ["Data Integrity", "Modeling & Research"], outcome: "NBA lineups REJECTED with evidence (no free official pre-start source; box-score starters are POST_START by definition) + the fail-closed six-class lineup contract that any future licensed adapter must satisfy", defectsFound: null, rollbackParent: "ad984c04d" },
  { program: "163", release: "A", commit: "ad984c04d", date: "2026-08-11", departments: ["Automation & Reliability", "Engineering & Architecture"], outcome: "four stale P162 gate watchers stopped (targets mapped terminal first, zero orphan pollers verified) + the bounded single-target watcher whose poll loop structurally cannot repeat the unfulfillable-predicate leak + operating runbook", defectsFound: "root cause named: newest-run polling filtered by a superseded SHA can never match again; harness timeouts are not enforced on backgrounded loops", rollbackParent: "0e0cea42d" },
  { program: "162", release: "J", commit: "e65f5f834", date: "2026-08-11", departments: ["Sport Operations", "Settlement & records"], outcome: "UFC results operational: capture + bout-id adapter through the corpus-validated contract; first real run quarantined all 12 pre-capture finals for lineage with exact reconciliation — the third sport to prove the lineage rule live", defectsFound: "the /sports assurance spec expected 'completed games' and UFC honestly says 'bouts' — caught on all three engines, regex now noun-aware", rollbackParent: "0aa27ecb0" },
  { program: "162", release: "I", commit: "aeabffe19", date: "2026-08-11", departments: ["Settlement & records"], outcome: "UFC bout_winner settlement contract validated on all 1,716 corpus finals — the 25 DRAW_OR_NC bouts are exactly the quarantines (winner-only source refuses to split draw from NC); every sport now carries a corpus-validated grading spec", defectsFound: null, rollbackParent: "e4d1d1e20" },
  { program: "162", release: "H", commit: "8e8d3b566", date: "2026-08-11", departments: ["Data Integrity", "Automation & Reliability"], outcome: "injuries capture live: first committed captures normalized 800+77 live entries with zero quarantines (facts only, prose never stored); NFL matrix entry AVAILABLE on the receipt; NBA half-receipt recorded not stretched; cadence step wired", defectsFound: "the P156 shadow-gap guard hard-coded the gap count — honest movement broke it; now derived from shadowGaps()", rollbackParent: "8dccfe2b4" },
  { program: "162", release: "G", commit: "8dccfe2b4", date: "2026-08-11", departments: ["Data Integrity"], outcome: "injuries contract: URL-derived athlete identity with refusal, closed taxonomies, absence=UNKNOWN never healthy, staleness widens; real-sample fixtures from the live probe", defectsFound: null, rollbackParent: "6ade60159" },
  { program: "162", release: "F", commit: "6ade60159", date: "2026-08-11", departments: ["Modeling & Research"], outcome: "injuries source evaluation ACCEPTED with two named conditions (identity validation; absence is not health); matrix notes upgraded without flipping states", defectsFound: null, rollbackParent: "de9afefce" },
  { program: "162", release: "E", commit: "de9afefce", date: "2026-08-11", departments: ["Settlement & records", "Sport Operations"], outcome: "EPL results-path hardening (kickoff move, alias both-directions, score-bearing non-finals, memoryless corrections, duplicates) + corrections runbook with the ledger-writer acceptance condition", defectsFound: "the alias case's premise was wrong — Arsenal FC is a committed alias and joins; the test now proves both directions", rollbackParent: "f70bdea51" },
  { program: "162", release: "closeout", commit: "f3cad466c", date: "2026-08-11", departments: ["Admin & Roadmap"], outcome: "roadmap deduplicated against REALITY_GATED watches (one issue, one card); evidence regenerated at wall clock", defectsFound: "the closeout commit itself claimed history entries an aborted edit never applied — caught by re-reading the diff stat, fixed in this follow-up", rollbackParent: "63f321127" },
  { program: "162", release: "B", commit: "63f321127", date: "2026-08-11", departments: ["Product & UX"], outcome: "results paths discoverable on /sports (per-sport artifact-state lines); undated 'coming soon' promise replaced with the stated absence condition; three-engine proof extended", defectsFound: "a guard pinned the stale phrase — repointed to the invariant and the phrase is now banned", rollbackParent: "e5a6ed7bd" },
  { program: "162", release: "D", commit: "e5a6ed7bd", date: "2026-08-11", departments: ["Sport Operations", "Data Integrity"], outcome: "UFC forward-lineage classifier (stable-id joins, basis-recorded corners, closed taxonomy) reproducing the real fight-day addition from committed captures", defectsFound: null, rollbackParent: "e7d98314e" },
  { program: "162", release: "C", commit: "e7d98314e", date: "2026-08-11", departments: ["Admin & Roadmap"], outcome: "/launch command center: health strip, REALITY_GATED watches with countdowns, derived sprint lanes, auditable release history with the mechanical pruning invariant", defectsFound: null, rollbackParent: "5e1027533" },
  { program: "162", release: "A", commit: "5e1027533", date: "2026-08-11", departments: ["Sport Operations", "Data Integrity"], outcome: "NBA results vertical: tied-final quarantine contract validated on 4,179 corpus finals (zero pushes), keyless capture + id-join adapter, cadence-wired; honest NO_RESULTS_YET off-season first receipt", defectsFound: "none — first live capture returned the truthful empty window", rollbackParent: "48a5094c4" },
  { program: "161", release: "closeout", commit: "af03ef1b4", date: "2026-08-11", departments: ["Admin & Roadmap"], outcome: "evidence ledger refreshed with the Aug 11 board + production run (13 entries, 0 contradictions)", defectsFound: null, rollbackParent: "96f31a1f4" },
  { program: "161", release: "D", commit: "96f31a1f4", date: "2026-08-11", departments: ["Sport Operations", "Settlement & records"], outcome: "NFL results side: FINAL-only tie=PUSH contract validated on 1,001 corpus finals; capture + snapshot-union id-join adapter; cadence-wired", defectsFound: "first live final (CAR-ARI Aug 7) predated schedule capture — quarantined for missing lineage, proving the Sprint-045 rule live", rollbackParent: "3efb9a11d" },
  { program: "161", release: "C", commit: "38c2b2e78", date: "2026-08-11", departments: ["QA & Accessibility", "Engineering & Architecture"], outcome: "three-engine route/state assurance: 8-route contract on chromium/webkit/firefox in every quality-gate run, money-strip artifact parity, closed state vocabularies", defectsFound: "homepage featured-sim cards requested ESPN logos by full team name (~10 CDN 404s per visit, hidden by the monogram fallback) — fixed by threading teamAbbrs", rollbackParent: "81192df8f" },
  { program: "161", release: "B", commit: "81192df8f", date: "2026-08-11", departments: ["Automation & Reliability", "Data Integrity"], outcome: "cadence receipt #2 processed per sport (runs 31396780843 + 31500117960); morning window bounded as ONE documented exception across three guards", defectsFound: "daily-products stamps today ~2h before board generation — money legitimately leads the board by one day every morning; frozen test clocks rot with the cadence", rollbackParent: "778082d30" },
  { program: "161", release: "A", commit: "bcec50d3a", date: "2026-08-11", departments: ["Engineering & Architecture"], outcome: "Simulation Hub non-promotion proofs: 7 metamorphic guards + wiring bans close every accidental-promotion vector", defectsFound: null, rollbackParent: null },
  { program: "160", release: "A", commit: "703a26e2e", date: "2026-08-10", departments: ["Data Integrity", "Admin & Roadmap"], outcome: "product-truth contract: one owner per public figure, fail-closed reconciliation, bounded documented exceptions", defectsFound: "cross-lane auditors initially added to LANE_DIRS — the readers-allowlist is the correct repoint shape", rollbackParent: null },
  { program: "159", release: "A", commit: "49bcc7220", date: "2026-08-10", departments: ["Engineering & Architecture", "Admin & Roadmap"], outcome: "route assurance inventory: 50 routes reconciled across source, ownership table, and built export — zero findings", defectsFound: null, rollbackParent: null },
  { program: "158", release: "A", commit: "a6b517388", date: "2026-08-10", departments: ["Product & UX"], outcome: "/sports information architecture: one Sports·Schedules destination across command rail, nav strip, footer, homepage strip", defectsFound: "a NAV_ITEMS-only destination is invisible at desktop widths — desktop wayfinding is the command rail", rollbackParent: null },
  { program: "157", release: "A", commit: "ccf37e3e8", date: "2026-08-10", departments: ["Modeling & Research"], outcome: "shared four-sport model registry: derived index echoing committed evaluations verbatim, INCOMPLETE-honest, ranking vocabulary banned", defectsFound: null, rollbackParent: null },
  { program: "156", release: "B", commit: "7032fe644", date: "2026-08-10", departments: ["Admin & Roadmap"], outcome: "shadowGaps wired into the work board — odds merged to ONE founder card spanning four sports", defectsFound: null, rollbackParent: null },
  { program: "155", release: "C+D", commit: "adac8cca1", date: "2026-08-10", departments: ["Admin & Roadmap", "Modeling & Research"], outcome: "board filters (read-only) + pipeline lanes + shadow contract with per-sport live-input matrix", defectsFound: null, rollbackParent: null },
  { program: "154", release: "A", commit: "e23f855dd", date: "2026-08-10", departments: ["Sport Operations", "Settlement & records"], outcome: "EPL current-results path operational before opening day: honest PRESEASON states, canonical join, quarantine-total", defectsFound: null, rollbackParent: null },
  { program: "153", release: "A+E", commit: "af554cbba", date: "2026-08-10", departments: ["Modeling & Research", "Admin & Roadmap"], outcome: "UFC research vertical (abstaining Elo, coverage 25.6% by design) + the /launch work board", defectsFound: "ESPN MMA endpoint rate-limits bursts — resumable fetcher with 15s spacing", rollbackParent: null },
  { program: "152", release: "A", commit: "4c2dbb032", date: "2026-08-10", departments: ["Modeling & Research", "Automation & Reliability"], outcome: "NBA research vertical (4,179 finals; leap-day + All-Star + Cup-final traps caught by exact-count refusals) + cadence receipt #1", defectsFound: "ESPN monthly windows miss leap days; season.year labels the end year", rollbackParent: null },
  { program: "151", release: "A+B", commit: "ed9e913df", date: "2026-08-10", departments: ["Modeling & Research", "Settlement & records"], outcome: "NFL research vertical (1,001 finals, 7 ties preserved) + EPL settlement validated on a full real season", defectsFound: "Pro Bowl AFC/NFC rows caught by the 32-team refusal", rollbackParent: null },
  { program: "150", release: "A", commit: "55fa6eb4c", date: "2026-08-09", departments: ["Sport Operations"], outcome: "NBA + UFC forward coverage live on /sports; four-sport daily cadence workflow", defectsFound: null, rollbackParent: null },
  { program: "149", release: "R1-R3", commit: "3d5cd6f8", date: "2026-08-09", departments: ["Modeling & Research", "Sport Operations"], outcome: "shared replay harness + strict artifact modes; EPL 380/380 capture with dual-source membership verification", defectsFound: "community source named two promoted clubs outside the committed alias table — quarantined, never auto-minted", rollbackParent: null },
  { program: "148", release: "B-D", commit: "118a1701d", date: "2026-08-09", departments: ["Product & UX", "Sport Operations"], outcome: "/sports revived as the four-sport schedule directory; NFL first real capture; EPL research corpus + baselines", defectsFound: null, rollbackParent: null },
  { program: "144-147", release: "A-I", commit: "281de088", date: "2026-08-08", departments: ["Engineering & Architecture", "Admin & Roadmap", "Product & UX"], outcome: "ledger v2, identity ratchet, provable-only Build compat, hour-aware labels, 12-stage sport gate (MLB sole LIVE_ELIGIBLE)", defectsFound: null, rollbackParent: null },
  { program: "141-143", release: "—", commit: null, date: "2026-08-07", departments: ["Engineering & Architecture"], outcome: "UNRECORDED in this register: these programs predate the release-history data structure; their receipts live in the program reports, not here — never invented retroactively", defectsFound: null, rollbackParent: null },
]);
