/**
 * THE WHOLE LIFECYCLE, DETERMINISTICALLY — pregame → live → final → settled (Phase 5 · V1).
 *
 * The provider payload is the real DET @ BUF response, replayed with its status rewritten to walk
 * the game through its phases. No network, no waiting for Sunday, and no mock inventing numbers:
 * the stats are the ones ESPN actually returned.
 *
 * Run: npx tsx --test src/lib/sports/nfl/live-prop-lifecycle.test.mjs
 */
import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { buildLiveRows, espnAthleteId, promoteFinality, selectLiveTargets, settle, shouldPollEvent, RECONCILIATION_WINDOW_MS } from "./live-prop-state.mjs";

const SUMMARY = JSON.parse(fs.readFileSync(path.join(process.cwd(), "src/lib/sports/nfl/__fixtures__/espn-nfl-summary-401872932.json"), "utf8"));
const hashOf = (o) => crypto.createHash("sha256").update(JSON.stringify(o)).digest("hex").slice(0, 16);
const EVENT = "401872932";
const KICKOFF = "2026-09-18T00:15:00Z";   // the real DET @ BUF kickoff
const STBROWN = "nfl-athlete-4374302";   // 9 rec, 142 yds, 2 rec TD

/** The committed board shape, with the two families we assert on. */
const board = (line) => ({
  generatedAt: "2026-09-17T14:00:00Z",
  players: [{
    playerId: STBROWN, name: "Amon-Ra St. Brown", team: "DET", participation: "AVAILABLE_ROLE_UNCERTAIN",
    markets: {
      player_reception_yds: { median: 79, p10: 41, p90: 118, market: { line, overOdds: -114, underOdds: -108, sportsbook: "draftkings", capturedAt: "2026-09-17T14:00:00Z" } },
      anytime_td: { median: null, market: { yesOdds: 135, sportsbook: "draftkings", capturedAt: "2026-09-17T14:00:00Z" } },
    },
  }],
});
const phased = (state) => {
  const s = structuredClone(SUMMARY);
  s.header.competitions[0].status = state === "pre"
    ? { type: { state: "pre", completed: false } }
    : state === "in"
      ? { type: { state: "in", completed: false }, displayClock: "8:42", period: 3 }
      : { type: { state: "post", completed: true } };
  return s;
};
const build = (state, prior, at) => buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: board(79.5), summary: phased(state), prior, observedAt: at, hashOf });
const row = (r, family) => r.rows.find((x) => x.family === family);

test("PREGAME emits no stat, no score, and no settlement", () => {
  const r = build("pre", null, "2026-09-17T23:00:00Z");
  const y = row(r, "player_reception_yds");
  assert.equal(y.live.phase, "PRE");
  assert.equal(y.live.statValue, null, "zero would be a measurement nobody took");
  assert.equal(y.live.score, null);
  assert.equal(y.settlement.state, "PENDING", "a game that has not started cannot settle");
  assert.equal(y.frozen.market.line, 79.5, "the frozen line is present from the first write");
});

test("LIVE reports the stat so far, the clock and the score — and still does not settle", () => {
  const r = build("in", null, "2026-09-18T01:30:00Z");
  const y = row(r, "player_reception_yds");
  assert.equal(y.live.phase, "IN_PROGRESS");
  assert.equal(y.live.statValue, 142);
  assert.equal(y.live.clock, "8:42");
  assert.equal(y.live.period, 3);
  assert.deepEqual(y.live.score, { home: 41, away: 31 });
  assert.equal(y.settlement.state, "PENDING", "an unfinished game never settles");
});

test("FINAL settles against the FROZEN line, across families", () => {
  const r = build("post", null, "2026-09-18T04:00:00Z");
  const y = row(r, "player_reception_yds");
  assert.equal(y.settlement.finalStat, 142);
  assert.equal(y.settlement.line, 79.5);
  assert.equal(y.settlement.lineResult, "OVER");
  const td = row(r, "anytime_td");
  assert.equal(td.settlement.lineResult, "YES", "he caught two — the anytime market settles yes");
});

test("⚠ A LATER RUN CANNOT REWRITE THE FROZEN BLOCK, EVEN WITH A NEWER BOARD", () => {
  /*
   * The board is regenerated by the event window and the odds capture keeps buying prices. Without
   * sealing, a line captured AFTER kickoff would replace the one a reader was shown and the whole
   * comparison would be against a number nobody saw.
   */
  const first = build("in", null, "2026-09-18T01:30:00Z");
  const movedLine = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: board(96.5), summary: phased("post"), prior: first, observedAt: "2026-09-18T04:00:00Z", hashOf });
  const y = row(movedLine, "player_reception_yds");
  assert.equal(y.frozen.market.line, 79.5, "the published line stands");
  assert.equal(y.frozen.market.capturedAt, "2026-09-17T14:00:00Z");
  /* ⚠ ONE, not two. The board carries two families for this player and only the reception-yards
     line moved; the anytime-TD block is identical, so it is correctly not counted as a refusal. I
     asserted 2 first — the counter is per PREDICTION whose frozen block would have changed, which
     is the number worth knowing, and a blunter count would hide which market actually moved. */
  assert.equal(movedLine.frozenRefusedNewerBoard, 1, "the refusal is COUNTED, not silently absorbed");
  assert.equal(row(movedLine, "anytime_td").frozen.market.yesOdds, 135, "an untouched family is untouched");
  assert.equal(y.settlement.line, 79.5, "settlement grades against the line we published");
  assert.equal(y.settlement.lineResult, "OVER");
});

test("⚠ SETTLEMENT HAPPENS ONCE — a re-read cannot restamp or re-grade it", () => {
  const settled = build("post", null, "2026-09-18T04:00:00Z");
  const again = build("post", settled, "2026-09-19T12:00:00Z");
  const a = row(settled, "player_reception_yds").settlement;
  const b = row(again, "player_reception_yds").settlement;
  for (const k of ["state", "finalStat", "line", "lineResult", "forecastResult", "settledAt"]) {
    assert.deepEqual(b[k], a[k], `the published ${k} is preserved`);
  }
  assert.equal(b.settledAt, "2026-09-18T04:00:00Z", "including WHEN it settled");
  /* ⚠ Only `finality` may advance — that is a statement about the reconciliation window, not about
     the grade. Everything a reader was shown is unchanged. */
  assert.equal(a.finality, "PROVISIONAL");
  assert.equal(b.finality, "CANONICAL", "a day later the window has closed");
});

test("⚠ PENDING IS NEVER A LOSS", () => {
  /* The dangerous shape: an unsettled prediction rendering as a graded miss. Pending is null. */
  for (const state of ["pre", "in"]) {
    const r = build(state, null, "2026-09-18T01:30:00Z");
    for (const x of r.rows) {
      assert.equal(x.settlement.state, "PENDING", `${state}: settlement must be PENDING, never a result`);
      assert.equal(x.settlement.lineResult, null, "and PENDING carries no direction that could read as a grade");
      assert.equal(x.settlement.forecastResult, null);
    }
  }
});

test("an athlete id that is not ours fails closed — no row, never a name fallback", () => {
  assert.equal(espnAthleteId("nfl-athlete-4374302"), "4374302");
  assert.equal(espnAthleteId("4374302"), null, "a bare number is not a durable board id");
  assert.equal(espnAthleteId("espn-4374302"), null);
  assert.equal(espnAthleteId(null), null);
  const bad = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, summary: phased("post"), observedAt: "x", hashOf,
    board: { generatedAt: "t", players: [{ playerId: "mlb-person-12345", name: "Wrong Sport", markets: { anytime_td: { median: 1 } } }] } });
  assert.deepEqual(bad.rows, [], "an unrecognised id produces no row at all");
});

test("a player the provider never reports gets NO fabricated progress", () => {
  const ghost = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, summary: phased("post"), observedAt: "2026-09-18T04:00:00Z", hashOf,
    board: { generatedAt: "2026-09-17T14:00:00Z", players: [{ playerId: "nfl-athlete-999999999", name: "Did Not Dress", markets: { player_rush_yds: { median: 40, market: { line: 38.5, sportsbook: "draftkings", capturedAt: "t" } } } }] } });
  const r = ghost.rows[0];
  assert.equal(r.live.statValue, null, "absent from every block is absent, not zero");
  assert.equal(r.settlement.state, "NO_MEASUREMENT", "⚠ and an absent measurement is NOT an Under, even at FINAL");
  assert.equal(r.settlement.lineResult, null);
});

test("the frozen identity is stable across runs that change nothing", () => {
  const a = build("in", null, "2026-09-18T01:30:00Z");
  const b = build("in", null, "2026-09-18T02:30:00Z");
  assert.equal(row(a, "player_reception_yds").frozenIdentity, row(b, "player_reception_yds").frozenIdentity,
    "an identity that moved on every observation could not detect a real change");
});

test("⚠ A POST-KICKOFF BOARD IS NEVER FROZEN RETROACTIVELY", () => {
  /*
   * ⚠ THIS PRODUCER ONLY RUNS AFTER KICKOFF, so the first write ALWAYS happens with the game under
   * way. Without a provenance check it would freeze whatever the board says at that moment —
   * including a board the event window regenerated mid-game and a price the odds capture bought
   * after the first snap. That is a post-kickoff line published as the pre-kickoff one: the exact
   * dishonesty the frozen slot exists to prevent, arriving through the front door.
   */
  const lateBoard = { ...board(79.5), generatedAt: "2026-09-18T01:00:00Z" }; // 45 min AFTER kickoff
  const r = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: lateBoard, summary: phased("in"), observedAt: "2026-09-18T01:30:00Z", hashOf });
  const y = row(r, "player_reception_yds");
  assert.equal(y.frozen, null, "no frozen block is minted from post-kickoff evidence");
  assert.match(y.frozenRefusal, /at or after kickoff/, "and the refusal says why, in words");
  assert.equal(r.frozenRefusedNoPregameSnapshot, 2, "both families refuse, and the refusal is counted");
  assert.equal(y.live.statValue, 142, "the LIVE state still renders — only the pregame claim is withheld");
  assert.equal(y.settlement.state, "PENDING");
});

test("a price captured after kickoff is refused even when the board predates it", () => {
  /* The board can be pregame while the odds capture that filled it is not. Both must predate. */
  const lateLine = {
    generatedAt: "2026-09-17T14:00:00Z",
    players: [{ playerId: STBROWN, name: "Amon-Ra St. Brown", team: "DET", participation: "P",
      markets: { player_reception_yds: { median: 79, p10: 41, p90: 118, market: { line: 79.5, sportsbook: "draftkings", capturedAt: "2026-09-18T00:40:00Z" } } } }],
  };
  const r = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: lateLine, summary: phased("in"), observedAt: "2026-09-18T01:30:00Z", hashOf });
  assert.equal(r.rows[0].frozen, null);
  assert.match(r.rows[0].frozenRefusal, /captured at .* at or after kickoff/);
});

test("⚠ A CORRECTED FINAL STAT IS RECORDED BESIDE THE SETTLEMENT, NOT OVER IT", () => {
  /*
   * Providers revise box scores. Overwriting loses what we published; refusing to look makes a real
   * correction invisible. The original settlement is the record and never changes; a later FINAL
   * observation that disagrees sits beside it with its own instant.
   */
  const settled = build("post", null, "2026-09-18T04:00:00Z");
  assert.equal(row(settled, "player_reception_yds").settlement.finalStat, 142);

  const corrected = structuredClone(SUMMARY);
  for (const tg of corrected.boxscore.players) {
    for (const st of tg.statistics) {
      if (st.name !== "receiving") continue;
      const a = st.athletes.find((x) => x.athlete.id === "4374302");
      if (a) a.stats[st.labels.indexOf("YDS")] = "138";   // the provider revises it down
    }
  }
  const after = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: board(79.5), summary: corrected, prior: settled, observedAt: "2026-09-19T12:00:00Z", hashOf });
  const y = row(after, "player_reception_yds");
  assert.equal(y.settlement.finalStat, 142, "what we published is unchanged");
  assert.equal(y.settlement.settledAt, "2026-09-18T04:00:00Z");
  assert.equal(y.reconciliation.finalStat, 138, "the correction is visible");
  assert.equal(y.reconciliation.differsFrom, 142, "and it says what it disagrees with");
  assert.equal(after.reconciled, 1);

  /* A re-run that agrees records nothing new. */
  const agreeing = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: board(79.5), summary: phased("post"), prior: settled, observedAt: "2026-09-19T13:00:00Z", hashOf });
  assert.equal(row(agreeing, "player_reception_yds").reconciliation, null, "an unchanged stat is not a correction");
});

test("NO_MEASUREMENT survives a re-run and never ripens into a loss", () => {
  const ghostBoard = { generatedAt: "2026-09-17T14:00:00Z", players: [{ playerId: "nfl-athlete-999999999", name: "Did Not Dress", participation: "CONFIRMED_OUT",
    markets: { player_rush_yds: { median: 40, market: { line: 38.5, sportsbook: "draftkings", capturedAt: "2026-09-17T14:00:00Z" } } } }] };
  const first = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: ghostBoard, summary: phased("post"), observedAt: "2026-09-18T04:00:00Z", hashOf });
  assert.equal(first.rows[0].settlement.state, "NO_MEASUREMENT");
  assert.equal(first.rows[0].settlement.participationAtFreeze, "CONFIRMED_OUT", "the participation we held is carried into the record");
  const again = buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: ghostBoard, summary: phased("post"), prior: first, observedAt: "2026-09-20T04:00:00Z", hashOf });
  const s2 = again.rows[0].settlement;
  assert.equal(s2.state, "NO_MEASUREMENT", "it is preserved, not re-graded into an Under on a later pass");
  assert.equal(s2.lineResult, null);
  assert.equal(s2.settledAt, first.rows[0].settlement.settledAt, "and it keeps the instant we first saw the absence");
  assert.equal(s2.finality, "CANONICAL", "two days later the window has closed and the absence is terminal");
});

/* A FINAL response whose receiving block omits, blanks, or reports our player. */
const finalWith = (mode) => {
  const s = phased("post");
  for (const tg of s.boxscore.players) {
    for (const st of tg.statistics) {
      if (st.name !== "receiving") continue;
      const i = st.athletes.findIndex((a) => a.athlete.id === "4374302");
      if (i < 0) continue;
      if (mode === "missing") st.athletes.splice(i, 1);
      else if (mode === "blank") st.athletes[i].stats = st.labels.map(() => "");
      else if (mode === "zero") st.athletes[i].stats = st.labels.map((l) => (l === "REC" ? "0" : l === "YDS" ? "0" : "0"));
      else if (mode === "eightySeven") st.athletes[i].stats[st.labels.indexOf("YDS")] = "87";
    }
  }
  return s;
};
const buildWith = (summary, prior, at) => buildLiveRows({ providerEventId: EVENT, kickoffUtc: KICKOFF, board: board(79.5), summary, prior, observedAt: at, hashOf });

test("⚠ FINAL #1 missing → NO_MEASUREMENT, and FINAL #2 reporting 0 RECONCILES it", () => {
  /*
   * ESPN can mark a game FINAL before every player block has published. Treating the first response
   * as terminal makes a merely-DELAYED player permanently ungraded — and because polling would have
   * stopped, no later observation could ever correct it.
   */
  const first = buildWith(finalWith("missing"), null, "2026-09-18T04:00:00Z");
  const a = row(first, "player_reception_yds").settlement;
  assert.equal(a.state, "NO_MEASUREMENT", "absent at the first FINAL read");
  assert.equal(a.finality, "PROVISIONAL", "⚠ but NOT terminal — the window is open");
  assert.equal(a.lineResult, null, "and never graded in the meantime");
  assert.equal(shouldPollEvent({ phase: "FINAL", finalFirstObservedAt: "2026-09-18T04:00:00Z", rows: first.rows }, "2026-09-18T04:30:00Z").poll, true,
    "so the game stays in the loop");

  /* ⚠ A LATE ZERO IS A REAL MEASUREMENT. He dressed, played, and caught nothing — that settles UNDER. */
  const second = buildWith(finalWith("zero"), first, "2026-09-18T05:00:00Z");
  const b = row(second, "player_reception_yds").settlement;
  assert.equal(b.state, "SETTLED");
  assert.equal(b.finalStat, 0);
  assert.equal(b.lineResult, "UNDER", "a measured zero is below a 79.5 line");
  assert.equal(b.recoveredFrom.state, "NO_MEASUREMENT", "and the record says it recovered from an absence");
  assert.equal(b.recoveredFrom.firstObservedAt, "2026-09-18T04:00:00Z");
  /* ⚠ TWO, not one. The player carries two families on this board and BOTH were absent at the first
     FINAL read, so both recover when he reappears — the anytime-TD row settles NO off the same
     receiving block. I asserted 1; the counter is per PREDICTION, which is the number worth having. */
  assert.equal(second.recoveredFromNoMeasurement, 2);
  assert.equal(row(second, "anytime_td").settlement.lineResult, "NO", "he reappeared with no touchdown");
});

test("⚠ FINAL #1 missing → NO_MEASUREMENT, and FINAL #2 reporting 87 RECONCILES it", () => {
  const first = buildWith(finalWith("missing"), null, "2026-09-18T04:00:00Z");
  assert.equal(row(first, "player_reception_yds").settlement.state, "NO_MEASUREMENT");

  const second = buildWith(finalWith("eightySeven"), first, "2026-09-18T05:00:00Z");
  const b = row(second, "player_reception_yds").settlement;
  assert.equal(b.state, "SETTLED");
  assert.equal(b.finalStat, 87);
  assert.equal(b.lineResult, "OVER", "87 clears a 79.5 line");
  /* ⚠ I asserted WIN here while the message beside it argued LOSS — the message was right. Our
     median 79 sits BELOW the 79.5 line, so our implied side was UNDER; the stat went OVER. */
  assert.equal(b.forecastResult, "LOSS", "we projected 79 against a 79.5 line — under — and it went over");
});

test("a blank cell at FINAL behaves like a missing one, and also reconciles", () => {
  const first = buildWith(finalWith("blank"), null, "2026-09-18T04:00:00Z");
  assert.equal(row(first, "player_reception_yds").settlement.state, "NO_MEASUREMENT",
    "⚠ Number(\"\") is 0 — a blank must not settle as a measured zero");
  const second = buildWith(finalWith("eightySeven"), first, "2026-09-18T05:30:00Z");
  assert.equal(row(second, "player_reception_yds").settlement.finalStat, 87);
});

test("a genuinely missing player reaches TERMINAL NO_MEASUREMENT, and polling stops", () => {
  /* The window is bounded, so this cannot poll forever — but it must not close early either. */
  let artifact = buildWith(finalWith("missing"), null, "2026-09-18T04:00:00Z");
  const mid = shouldPollEvent({ phase: "FINAL", finalFirstObservedAt: "2026-09-18T04:00:00Z", rows: artifact.rows }, "2026-09-18T06:00:00Z");
  assert.equal(mid.poll, true, "two hours in, a late stat can still arrive");

  artifact = buildWith(finalWith("missing"), artifact, "2026-09-18T07:30:00Z");   // past the 3h window
  const s = row(artifact, "player_reception_yds").settlement;
  assert.equal(s.state, "NO_MEASUREMENT");
  assert.equal(s.finality, "CANONICAL", "the window closed and the absence is now terminal");
  assert.equal(s.settledAt, "2026-09-18T04:00:00Z", "it keeps the instant we first saw the absence");
  assert.equal(s.lineResult, null, "and is never graded, at any point");

  const done = shouldPollEvent({ phase: "FINAL", finalFirstObservedAt: "2026-09-18T04:00:00Z", rows: artifact.rows }, "2026-09-18T07:30:00Z");
  assert.equal(done.poll, false, "polling terminates deterministically");
  assert.match(done.reason, /window closed/);
});

test("a canonical absence is never re-opened by a later read", () => {
  const first = buildWith(finalWith("missing"), null, "2026-09-18T04:00:00Z");
  const closed = buildWith(finalWith("missing"), first, "2026-09-18T08:00:00Z");
  assert.equal(row(closed, "player_reception_yds").settlement.finality, "CANONICAL");
  /* Even if the provider later produces a figure, the window has closed and the record stands. */
  const tooLate = buildWith(finalWith("eightySeven"), closed, "2026-09-19T12:00:00Z");
  const s = row(tooLate, "player_reception_yds").settlement;
  assert.equal(s.state, "NO_MEASUREMENT", "a closed window is closed — the terminal record stands");
  assert.equal(s.finality, "CANONICAL");
});

/* ── THE TARGET SET (Phase C · 2026-09-25) ─────────────────────────────────────────────────────── */

test("⚠ A FORWARD-ONLY SCHEDULE CANNOT CHOOSE THE LIVE GAMES — it drops them at kickoff", () => {
  /*
   * THE DEFECT. The producer selected targets from `nfl/schedule/latest.json`, which holds only
   * FUTURE kickoffs: `capture-nfl-schedule.mjs` filters with `inWindow(e.date, d0, d1)` where
   * `d0 = new Date(NOW)` — the capture INSTANT — so a game that has kicked off is gone the next time
   * the schedule is captured. The producer wants `kickoff <= now`. The two are mutually exclusive, and
   * the lane only ever found a game while the schedule happened to be stale relative to kickoff.
   *
   * The real artifact on 2026-09-25: generated 14:34:12Z, 17 rows, earliest kickoff 2026-09-27 —
   * Thursday's 00:15Z game absent, while its committed board was still on disk. With delivery here
   * running 1h40m to 4h55m late, a capture landing after the first Sunday kickoff would empty the
   * target set for the rest of the slate and nothing would ever settle, while the log read
   * "nothing to track".
   */
  const kickoff = "2026-09-27T17:00Z";
  const boards = [{ providerEventId: "401872953", kickoffUtc: kickoff, matchup: "LAC @ BUF" }];
  const nowMs = Date.parse("2026-09-27T19:30:00Z");   // 2h30m into the game

  // A schedule recaptured mid-slate no longer contains the game at all. That must NOT hide it.
  const recaptured = selectLiveTargets({ boards, scheduleRows: [], nowMs });
  assert.deepEqual(recaptured.disagreements, [], "a game the schedule has moved past is not a conflict");
  assert.equal(recaptured.targets.length, 1, "a started game stays trackable when the schedule has dropped it");
  assert.equal(recaptured.targets[0].providerEventId, "401872953");
  assert.equal(recaptured.targets[0].shortName, "LAC @ BUF", "labelled from the board's own matchup");

  // And it behaves identically when the schedule does still carry it.
  const stillListed = selectLiveTargets({
    boards,
    scheduleRows: [{ providerEventId: "401872953", dateUtc: kickoff }],
    nowMs,
  });
  assert.equal(stillListed.targets.length, 1, "and it is the same answer either way");
});

test("the live window opens at kickoff and closes eight hours later", () => {
  const boards = [{ providerEventId: "1", kickoffUtc: "2026-09-27T17:00Z", matchup: "A @ B" }];
  const at = (iso) => selectLiveTargets({ boards, scheduleRows: [], nowMs: Date.parse(iso) }).targets.length;

  assert.equal(at("2026-09-27T16:59:59Z"), 0, "a pre-kickoff read carries no stat and no score — do not fetch it");
  assert.equal(at("2026-09-27T17:00:00Z"), 1, "open at kickoff");
  assert.equal(at("2026-09-27T20:00:00Z"), 1, "still open mid-game");
  assert.equal(at("2026-09-28T01:00:00Z"), 1, "open at eight hours");
  assert.equal(at("2026-09-28T01:00:01Z"), 0, "closed after eight hours — this is what bounds it to one slate");

  // The short and long ISO forms are ONE instant; a board writes the short one.
  const long = [{ providerEventId: "1", kickoffUtc: "2026-09-27T17:00:00Z", matchup: "A @ B" }];
  assert.equal(
    selectLiveTargets({ boards: long, scheduleRows: [], nowMs: Date.parse("2026-09-27T18:00:00Z") }).targets.length, 1,
    "`T17:00Z` and `T17:00:00Z` must not be different kickoffs",
  );
});

test("⚠ two canonical artifacts disagreeing about kickoff REFUSES — and is not silently preferred", () => {
  /*
   * The schedule's forward filter is expected and benign. A schedule that still lists the game but at
   * a DIFFERENT instant is not: one of the two is wrong, and attaching live state to the wrong fixture
   * is the failure this whole lane exists to prevent. The caller must refuse, so the row is returned
   * rather than dropped quietly, and the game is excluded from the targets either way.
   */
  const boards = [{ providerEventId: "1", kickoffUtc: "2026-09-27T17:00Z", matchup: "A @ B" }];
  const out = selectLiveTargets({
    boards,
    scheduleRows: [{ providerEventId: "1", dateUtc: "2026-09-27T20:15Z" }],
    nowMs: Date.parse("2026-09-27T19:30:00Z"),
  });
  assert.equal(out.disagreements.length, 1, "the conflict is reported, not resolved by picking one");
  assert.match(out.disagreements[0], /board 2026-09-27T17:00Z vs schedule 2026-09-27T20:15:00/);
  assert.deepEqual(out.targets, [], "and the contested fixture is not tracked");
});

test("a board with no id or an unreadable kickoff contributes nothing", () => {
  const nowMs = Date.parse("2026-09-27T19:30:00Z");
  for (const bad of [
    { kickoffUtc: "2026-09-27T17:00Z" },                       // no event id
    { providerEventId: "1" },                                   // no kickoff
    { providerEventId: "1", kickoffUtc: "not a date" },
    { providerEventId: "1", kickoffUtc: null },
  ]) {
    assert.deepEqual(selectLiveTargets({ boards: [bad], scheduleRows: [], nowMs }).targets, [], JSON.stringify(bad));
  }
  // A numeric provider id is still the same event as its string form.
  assert.equal(
    selectLiveTargets({ boards: [{ providerEventId: 401872953, kickoffUtc: "2026-09-27T17:00Z" }], scheduleRows: [{ providerEventId: "401872953", dateUtc: "2026-09-27T17:00Z" }], nowMs }).targets.length,
    1, "a number and a string id must not read as two fixtures",
  );
});

// ══ PROVISIONAL → CANONICAL: THE TERMINUS THAT HAD NEVER BEEN REACHED ═══════════════════════════
//
// Both clocks were the same clock: the producer polled only while `finalityAt` said PROVISIONAL and
// stamped whatever it said at that same instant, so every moment that would have written CANONICAL
// was a moment nothing was written. `finalityAt` was correct and tested; the COMPOSITION was the bug.

test("⚠ the window closing yields promote, not silence — CANONICAL is reachable", () => {
  const ffo = "2026-09-25T03:30:00Z";
  const prior = { phase: "FINAL", finalFirstObservedAt: ffo, finality: "PROVISIONAL", rows: [{ settlement: { state: "SETTLED", finality: "PROVISIONAL" } }] };
  const before = new Date(Date.parse(ffo) + RECONCILIATION_WINDOW_MS - 60_000).toISOString();
  const after = new Date(Date.parse(ffo) + RECONCILIATION_WINDOW_MS + 60_000).toISOString();

  const open = shouldPollEvent(prior, before);
  assert.equal(open.poll, true);
  assert.equal(open.promote, false, "nothing is promoted while a late stat can still arrive");

  const closed = shouldPollEvent(prior, after);
  assert.equal(closed.poll, false, "a closed window must not reopen polling");
  assert.equal(closed.promote, true, "…but it must not be silent either — that is what made CANONICAL dead");

  // Already promoted: neither poll nor promote. Otherwise every later run rewrites the artifact.
  const done = shouldPollEvent({ ...prior, finality: "CANONICAL" }, after);
  assert.equal(done.poll, false);
  assert.equal(done.promote, false);
});

test("⚠ promoteFinality advances finality and NOTHING else — not a grade, not an instant", () => {
  const ffo = "2026-09-25T03:30:00Z";
  const after = new Date(Date.parse(ffo) + RECONCILIATION_WINDOW_MS + 60_000).toISOString();
  const prior = {
    phase: "FINAL", finalFirstObservedAt: ffo, finality: "PROVISIONAL", observedAt: ffo,
    rows: [
      { predictionId: "p1", frozen: { projection: { median: 63 } }, live: { statValue: 194 }, settlement: { state: "SETTLED", finalStat: 194, lineResult: "OVER", forecastResult: "WIN", settledAt: ffo, finality: "PROVISIONAL" } },
      { predictionId: "p2", frozen: { projection: { median: 10 } }, live: { statValue: null }, settlement: { state: "NO_MEASUREMENT", finalStat: null, settledAt: ffo, finality: "PROVISIONAL" } },
      { predictionId: "p3", frozen: null },   // no settlement at all — must pass through untouched
    ],
  };
  const next = promoteFinality(prior, after);
  assert.equal(next.finality, "CANONICAL");
  assert.deepEqual(next.rows.map((r) => r.settlement?.finality ?? null), ["CANONICAL", "CANONICAL", null]);

  // Everything that is not `finality` is byte-identical.
  const strip = (a) => JSON.stringify({ ...a, finality: 0, rows: a.rows.map((r) => (r.settlement ? { ...r, settlement: { ...r.settlement, finality: 0 } } : r)) });
  assert.equal(strip(next), strip(prior), "a promotion that can change a result is a re-grade wearing a clock's clothes");

  assert.equal(promoteFinality(next, after), null, "idempotent");
  assert.equal(promoteFinality(prior, new Date(Date.parse(ffo) + RECONCILIATION_WINDOW_MS - 1).toISOString()), null, "not before the window closes");
  assert.equal(promoteFinality({ ...prior, phase: "IN_PROGRESS" }, after), null, "never for a game still in progress");
  assert.equal(promoteFinality({ ...prior, finalFirstObservedAt: null }, after), null, "no first-final instant means no window to close");
});

// ══ A FORECAST IS GRADED ONLY WHERE IT WAS PUBLISHED ═══════════════════════════════════════════
//
// ⚠ NOT HYPOTHETICAL. On the 2026-09-27 boards `player_pass_yds` is ESTIMATE and twenty-eight of its
// entries carry a frozen line anyway — the odds capture buys prices per market and never consults a
// model verdict. The only reason nothing had been graded yet is that the one completed game's four
// ESTIMATE rows happened to have no line. That is luck, not a rule.

test("⚠ an unpublished family gets the FACT but never the CLAIM", () => {
  const ESPN = "4374302";                        // St. Brown: 142 reception yards, real payload
  const args = { summary: phased("post"), espnId: ESPN, family: "player_reception_yds", frozenLine: 79.5, projection: 79, settledAt: "2026-09-18T04:00:00Z" };

  const published = settle({ ...args, familyState: "PUBLISHED" });
  assert.equal(published.lineResult, "OVER", "142 is over 79.5");
  assert.equal(published.forecastResult, "LOSS", "we projected 79 against a 79.5 line — UNDER — and it went over");

  for (const state of ["ESTIMATE", "WITHHELD", "STOPPED"]) {
    const r = settle({ ...args, familyState: state });
    assert.equal(r.lineResult, "OVER", `${state}: the final stat against the frozen line is a fact either way`);
    assert.equal(r.forecastResult, "NOT_PUBLISHED", `${state}: no track record for a model we chose not to show`);
  }

  // An artifact with no label keeps the previous behaviour rather than silently refusing to grade a
  // family that WAS published.
  assert.equal(settle({ ...args, familyState: null }).forecastResult, "LOSS");
});

test("⚠ buildLiveRows THREADS the board's family state — the gate must survive the real call path", () => {
  const withStates = (state) => ({
    ...board(79.5),
    families: { player_reception_yds: { state }, anytime_td: { state: "PUBLISHED" } },
  });
  const run = (state) => buildLiveRows({
    providerEventId: EVENT, kickoffUtc: KICKOFF, board: withStates(state),
    summary: phased("post"), prior: null, observedAt: "2026-09-18T04:00:00Z", hashOf,
  });
  assert.equal(row(run("PUBLISHED"), "player_reception_yds").settlement.forecastResult, "LOSS");
  assert.equal(row(run("ESTIMATE"), "player_reception_yds").settlement.forecastResult, "NOT_PUBLISHED");
});

// ══ A CONTESTED FIXTURE IS EXCLUDED, NOT A REASON TO ABANDON THE SLATE ═════════════════════════

test("⚠ one moved fixture excludes ITSELF and the rest of the slate still runs", () => {
  const boards = [
    { providerEventId: "1", kickoffUtc: "2026-09-27T17:00:00Z", matchup: "A @ B" },
    { providerEventId: "2", kickoffUtc: "2026-09-27T17:05:00Z", matchup: "C @ D" },   // schedule says 17:00
    { providerEventId: "3", kickoffUtc: "2026-09-27T17:00:00Z", matchup: "E @ F" },
  ];
  const scheduleRows = boards.map((b) => ({ providerEventId: b.providerEventId, dateUtc: "2026-09-27T17:00:00Z" }));
  const r = selectLiveTargets({ boards, scheduleRows, nowMs: Date.parse("2026-09-27T18:00:00Z") });

  assert.equal(r.verdict, "PROCEED_EXCLUDING_CONTESTED");
  assert.equal(r.disagreements.length, 1);
  assert.deepEqual(r.targets.map((t) => t.providerEventId), ["1", "3"], "the other two games are untouched");
});

test("⚠ but a capture that reconciles with NOTHING still refuses", () => {
  const boards = [
    { providerEventId: "1", kickoffUtc: "2026-09-27T17:05:00Z", matchup: "A @ B" },
    { providerEventId: "2", kickoffUtc: "2026-09-27T17:05:00Z", matchup: "C @ D" },
  ];
  const scheduleRows = boards.map((b) => ({ providerEventId: b.providerEventId, dateUtc: "2026-09-27T17:00:00Z" }));
  const r = selectLiveTargets({ boards, scheduleRows, nowMs: Date.parse("2026-09-27T18:00:00Z") });
  assert.equal(r.verdict, "REFUSE_UNRECONCILABLE");
  assert.equal(r.targets.length, 0);
});

test("⚠ AND A QUIET TUESDAY IS NOT AN UNRECONCILABLE CAPTURE — the verdict asks about reconciliation, not the clock", () => {
  const boards = [{ providerEventId: "1", kickoffUtc: "2026-09-27T17:00:00Z", matchup: "A @ B" },
                  { providerEventId: "2", kickoffUtc: "2026-09-27T17:05:00Z", matchup: "C @ D" }];
  const scheduleRows = boards.map((b) => ({ providerEventId: b.providerEventId, dateUtc: "2026-09-27T17:00:00Z" }));
  const r = selectLiveTargets({ boards, scheduleRows, nowMs: Date.parse("2026-09-30T12:00:00Z") });   // days later
  assert.equal(r.targets.length, 0, "nothing is in the live window");
  assert.equal(r.verdict, "PROCEED_EXCLUDING_CONTESTED", "a target count of zero must not be read as a broken capture");
});

test("no disagreement at all is a plain PROCEED", () => {
  const boards = [{ providerEventId: "1", kickoffUtc: "2026-09-27T17:00Z", matchup: "A @ B" }];
  const r = selectLiveTargets({ boards, scheduleRows: [{ providerEventId: "1", dateUtc: "2026-09-27T17:00:00Z" }], nowMs: Date.parse("2026-09-27T18:00:00Z") });
  assert.equal(r.verdict, "PROCEED");
  assert.equal(r.usableCount, 1);
  assert.equal(r.targets.length, 1, "the short and long ISO forms are one instant");
});
