/**
 * THE WHOLE LIFECYCLE, DETERMINISTICALLY — pregame → live → final → settled (Phase 5 · V1).
 *
 * The provider payload is the real DET @ BUF response, replayed with its status rewritten to walk
 * the game through its phases. No network, no waiting for Sunday, and no mock inventing numbers:
 * the stats are the ones ESPN actually returned.
 *
 * Run: npx tsx --test src/lib/sports/nfl/live-prop-lifecycle.test.mjs
 */
import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { buildLiveRows, espnAthleteId } from "./live-prop-state.mjs";

const SUMMARY = JSON.parse(fs.readFileSync(path.join(process.cwd(), "src/lib/sports/nfl/__fixtures__/espn-nfl-summary-401872932.json"), "utf8"));
const hashOf = (o) => crypto.createHash("sha256").update(JSON.stringify(o)).digest("hex").slice(0, 16);
const EVENT = "401872932";
const STBROWN = "nfl-athlete-4374302";   // 9 rec, 142 yds, 2 rec TD

/** The committed board shape, with the two families we assert on. */
const board = (line) => ({
  generatedAt: "2026-09-17T14:00:00Z",
  players: [{
    playerId: STBROWN, name: "Amon-Ra St. Brown", team: "DET", participation: "AVAILABLE_ROLE_UNCERTAIN",
    markets: {
      player_reception_yds: { median: 79, p10: 41, p90: 118, market: { line, overOdds: -114, underOdds: -108, sportsbook: "draftkings", capturedAt: "2026-09-17T14:00:00Z" } },
      anytime_td: { median: null, market: { yesOdds: 135, sportsbook: "draftkings", capturedAt: "2026-09-17T14:00:00Z" } },
    },
  }],
});
const phased = (state) => {
  const s = structuredClone(SUMMARY);
  s.header.competitions[0].status = state === "pre"
    ? { type: { state: "pre", completed: false } }
    : state === "in"
      ? { type: { state: "in", completed: false }, displayClock: "8:42", period: 3 }
      : { type: { state: "post", completed: true } };
  return s;
};
const build = (state, prior, at) => buildLiveRows({ providerEventId: EVENT, board: board(79.5), summary: phased(state), prior, observedAt: at, hashOf });
const row = (r, family) => r.rows.find((x) => x.family === family);

test("PREGAME emits no stat, no score, and no settlement", () => {
  const r = build("pre", null, "2026-09-17T23:00:00Z");
  const y = row(r, "player_reception_yds");
  assert.equal(y.live.phase, "PRE");
  assert.equal(y.live.statValue, null, "zero would be a measurement nobody took");
  assert.equal(y.live.score, null);
  assert.equal(y.settlement, null, "a game that has not started cannot settle");
  assert.equal(y.frozen.market.line, 79.5, "the frozen line is present from the first write");
});

test("LIVE reports the stat so far, the clock and the score — and still does not settle", () => {
  const r = build("in", null, "2026-09-18T01:30:00Z");
  const y = row(r, "player_reception_yds");
  assert.equal(y.live.phase, "IN_PROGRESS");
  assert.equal(y.live.statValue, 142);
  assert.equal(y.live.clock, "8:42");
  assert.equal(y.live.period, 3);
  assert.deepEqual(y.live.score, { home: 41, away: 31 });
  assert.equal(y.settlement, null, "an unfinished game never settles");
});

test("FINAL settles against the FROZEN line, across families", () => {
  const r = build("post", null, "2026-09-18T04:00:00Z");
  const y = row(r, "player_reception_yds");
  assert.equal(y.settlement.finalStat, 142);
  assert.equal(y.settlement.line, 79.5);
  assert.equal(y.settlement.lineResult, "OVER");
  const td = row(r, "anytime_td");
  assert.equal(td.settlement.yesResult, true, "he caught two — the anytime market settles yes");
});

test("⚠ A LATER RUN CANNOT REWRITE THE FROZEN BLOCK, EVEN WITH A NEWER BOARD", () => {
  /*
   * The board is regenerated by the event window and the odds capture keeps buying prices. Without
   * sealing, a line captured AFTER kickoff would replace the one a reader was shown and the whole
   * comparison would be against a number nobody saw.
   */
  const first = build("in", null, "2026-09-18T01:30:00Z");
  const movedLine = buildLiveRows({ providerEventId: EVENT, board: board(96.5), summary: phased("post"), prior: first, observedAt: "2026-09-18T04:00:00Z", hashOf });
  const y = row(movedLine, "player_reception_yds");
  assert.equal(y.frozen.market.line, 79.5, "the published line stands");
  assert.equal(y.frozen.market.capturedAt, "2026-09-17T14:00:00Z");
  /* ⚠ ONE, not two. The board carries two families for this player and only the reception-yards
     line moved; the anytime-TD block is identical, so it is correctly not counted as a refusal. I
     asserted 2 first — the counter is per PREDICTION whose frozen block would have changed, which
     is the number worth knowing, and a blunter count would hide which market actually moved. */
  assert.equal(movedLine.frozenRefusedNewerBoard, 1, "the refusal is COUNTED, not silently absorbed");
  assert.equal(row(movedLine, "anytime_td").frozen.market.yesOdds, 135, "an untouched family is untouched");
  assert.equal(y.settlement.line, 79.5, "settlement grades against the line we published");
  assert.equal(y.settlement.lineResult, "OVER");
});

test("⚠ SETTLEMENT HAPPENS ONCE — a re-read cannot restamp or re-grade it", () => {
  const settled = build("post", null, "2026-09-18T04:00:00Z");
  const again = build("post", settled, "2026-09-19T12:00:00Z");
  const a = row(settled, "player_reception_yds").settlement;
  const b = row(again, "player_reception_yds").settlement;
  assert.deepEqual(b, a, "the original settlement is preserved byte for byte");
  assert.equal(b.settledAt, "2026-09-18T04:00:00Z", "including WHEN it settled");
});

test("⚠ PENDING IS NEVER A LOSS", () => {
  /* The dangerous shape: an unsettled prediction rendering as a graded miss. Pending is null. */
  for (const state of ["pre", "in"]) {
    const r = build(state, null, "2026-09-18T01:30:00Z");
    for (const x of r.rows) {
      assert.equal(x.settlement, null, `${state}: settlement must be null, never a result`);
      assert.ok(!("lineResult" in x), "a row carries no top-level result that could read as a grade");
    }
  }
});

test("an athlete id that is not ours fails closed — no row, never a name fallback", () => {
  assert.equal(espnAthleteId("nfl-athlete-4374302"), "4374302");
  assert.equal(espnAthleteId("4374302"), null, "a bare number is not a durable board id");
  assert.equal(espnAthleteId("espn-4374302"), null);
  assert.equal(espnAthleteId(null), null);
  const bad = buildLiveRows({ providerEventId: EVENT, summary: phased("post"), observedAt: "x", hashOf,
    board: { generatedAt: "t", players: [{ playerId: "mlb-person-12345", name: "Wrong Sport", markets: { anytime_td: { median: 1 } } }] } });
  assert.deepEqual(bad.rows, [], "an unrecognised id produces no row at all");
});

test("a player the provider never reports gets NO fabricated progress", () => {
  const ghost = buildLiveRows({ providerEventId: EVENT, summary: phased("post"), observedAt: "2026-09-18T04:00:00Z", hashOf,
    board: { generatedAt: "t", players: [{ playerId: "nfl-athlete-999999999", name: "Did Not Dress", markets: { player_rush_yds: { median: 40, market: { line: 38.5, sportsbook: "draftkings", capturedAt: "t" } } } }] } });
  const r = ghost.rows[0];
  assert.equal(r.live.statValue, null, "absent from every block is absent, not zero");
  assert.equal(r.settlement, null, "and an absent measurement never settles, even at FINAL");
});

test("the frozen identity is stable across runs that change nothing", () => {
  const a = build("in", null, "2026-09-18T01:30:00Z");
  const b = build("in", null, "2026-09-18T02:30:00Z");
  assert.equal(row(a, "player_reception_yds").frozenIdentity, row(b, "player_reception_yds").frozenIdentity,
    "an identity that moved on every observation could not detect a real change");
});
