/**
 * P2-C · reader-facing model copy that had drifted from the truth it describes (map: docs/PUBLICATION_MAP_2026-09-29.md).
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const read = (rel) => fs.readFileSync(path.join(process.cwd(), rel), "utf8");

test("NFL product copy does not call a regular-season model a 'preseason beta'", () => {
  const code = read("src/lib/sports/nfl/product-eligibility.mjs").replace(/^\s*\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");
  assert.doesNotMatch(code, /preseason beta/);
  assert.doesNotMatch(read("public/data/nfl/product-eligibility.json"), /preseason beta/, "regenerated by its producer");
});

test("the EPL scorer lists do not claim no availability feed exists (FPL publishes one; it is not joined yet)", () => {
  assert.doesNotMatch(read("scripts/epl/build-epl-player-projections.mjs"), /No injury or suspension feed exists/);
  assert.match(read("scripts/epl/build-epl-player-projections.mjs"), /not joined into these lists yet/);
});

test("the Ligue 1 artifact describes the engine it actually uses", () => {
  const src = read("scripts/soccer/build-league-forecasts.mjs");
  assert.doesNotMatch(src, /the model the Premier League page publishes/, "the EPL page publishes v2; this uses EPL_MODEL_ID (v1)");
  assert.match(src, /split-Poisson model \(v1\)/);
  assert.match(read("src/lib/sports/epl/strength-state.mjs"), /EPL_MODEL_ID = "epl-model-v1-split-poisson"/, "the description stays tied to the id it names");
});
