#!/usr/bin/env bash
# ============================================================================
# GametimePicks — smoke test (Phase 7B-1.1)
#
# Verifies that the project is in a runnable state. Designed to be cheap
# and idempotent. Run it before pushing to GitHub or deploying to Vercel.
#
# IMPORTANT — Phase 7B-1.1 fix: this smoke test NEVER overwrites the
# production JSON files in app/public/data/. It runs the pipeline into a
# temporary output directory and validates the output there. The real
# production JSON is generated by scripts/run_pipeline.sh (or by the
# apply script in auto mode). This separation prevents a "smoke test
# clobbers real schedule with demo data" footgun.
#
# Checks:
#   1. Pipeline runs end-to-end into /tmp (forced demo for portability)
#   2. Production JSON files exist in app/public/data/
#   3. JSON files parse cleanly
#   4. Frontend data contract — meta + board + slate shape
#   5. Required public assets exist
#
# Exits non-zero on first failure.
# ============================================================================

set -e

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

PASS="\033[0;32m✓\033[0m"
FAIL="\033[0;31m✗\033[0m"
INFO="\033[0;34m·\033[0m"

ok()   { echo -e "  ${PASS} $1"; }
err()  { echo -e "  ${FAIL} $1" >&2; exit 1; }
info() { echo -e "  ${INFO} $1"; }

echo ""
echo "=========================================="
echo "  GametimePicks — smoke test"
echo "=========================================="

# ---------------------------------------------------------------------------
# 1. Pipeline runs end-to-end (into /tmp, NOT touching production JSON)
# ---------------------------------------------------------------------------
echo ""
echo "[1/5] Pipeline run (demo, scratch dir)"

SCRATCH=$(mktemp -d -t gtp_smoke_XXXX)
info "scratch dir: $SCRATCH"

# Force demo + write to scratch — does NOT overwrite app/public/data
if NBA_DATA_MODE=demo ODDS_DATA_MODE=demo GTP_DATA_OUT="$SCRATCH" \
    python3 -m pipeline.generate_daily_board > /tmp/gtp_smoke.log 2>&1; then
    ok "pipeline ran without errors"
else
    cat /tmp/gtp_smoke.log
    rm -rf "$SCRATCH"
    err "pipeline failed"
fi

# Verify scratch output looks right
if [ ! -f "$SCRATCH/board.json" ] || [ ! -f "$SCRATCH/slate.json" ]; then
    rm -rf "$SCRATCH"
    err "pipeline scratch output missing core files"
fi
ok "scratch board.json + slate.json present"

# Cleanup scratch
rm -rf "$SCRATCH"

# ---------------------------------------------------------------------------
# 2. Required production JSON files exist
# ---------------------------------------------------------------------------
echo ""
echo "[2/5] Required production JSON files"

REQUIRED_FILES=(
    "app/public/data/board.json"
    "app/public/data/schedule.json"
    "app/public/data/players.json"
    "app/public/data/odds_props.json"
    "app/public/data/meta.json"
    "app/public/data/slate.json"
)

for f in "${REQUIRED_FILES[@]}"; do
    if [ -f "$f" ]; then
        size=$(stat -f%z "$f" 2>/dev/null || stat -c%s "$f" 2>/dev/null)
        ok "$f (${size} bytes)"
    else
        err "missing: $f — run 'bash scripts/run_pipeline.sh' first"
    fi
done

# ---------------------------------------------------------------------------
# 3. JSON validity
# ---------------------------------------------------------------------------
echo ""
echo "[3/5] JSON validity"

for f in "${REQUIRED_FILES[@]}"; do
    if python3 -c "import json; json.load(open('$f'))" 2>/dev/null; then
        ok "$f parses"
    else
        err "$f does not parse as JSON"
    fi
done

# ---------------------------------------------------------------------------
# 4. Frontend data contract — meta + board + slate
# ---------------------------------------------------------------------------
echo ""
echo "[4/5] Frontend data contract"

python3 << 'PYEOF' || err "frontend contract check failed"
import json, sys, os

# meta.json must have these keys for the DataSourceBadge to render correctly
meta = json.load(open("app/public/data/meta.json"))
required_meta = [
    "appName", "version", "lastPipelineRun", "isDemo",
    "dataMode", "nbaScheduleSource", "oddsSource",
    "providerStatuses", "fallbackSourcesAvailable",
]
missing = [k for k in required_meta if k not in meta]
if missing:
    print(f"  ✗ meta.json missing keys: {missing}", file=sys.stderr)
    sys.exit(1)

if len(meta.get("providerStatuses", [])) < 4:
    print(f"  ✗ meta.json providerStatuses too short: {len(meta.get('providerStatuses', []))}", file=sys.stderr)
    sys.exit(1)

# board.json must have dataMode (Phase 7B-1.1 contract)
board = json.load(open("app/public/data/board.json"))
if "dataMode" not in board:
    print("  ✗ board.json missing 'dataMode' field (Phase 7B-1.1 contract)", file=sys.stderr)
    sys.exit(1)

valid_modes = {
    "Live", "ScheduleLiveOddsUnavailable", "NoGames",
    "ScheduleUnavailable", "DemoForced",
}
if board["dataMode"] not in valid_modes:
    print(f"  ✗ board.json dataMode '{board['dataMode']}' not in {valid_modes}", file=sys.stderr)
    sys.exit(1)

# Phase 7B-1.2: parser-drop guard
# If the provider reported success and raw count > 0, parsed count must be > 0
if board.get("scheduleFetchSucceeded") and board.get("rawGameCountBeforeFiltering", 0) > 0:
    if board.get("parsedGameCountAfterFiltering", 0) == 0:
        print(
            f"  ✗ board.json parser dropped all games: "
            f"raw={board['rawGameCountBeforeFiltering']} parsed=0 — "
            f"this is the May 4 bug, never accept it",
            file=sys.stderr,
        )
        sys.exit(1)

# Phase 7B-2.1: NoGames requires multi-source confirmation
if board["dataMode"] == "NoGames":
    if board.get("scheduleProviderStatus") != "ok":
        print(
            f"  ✗ board.json NoGames mode requires scheduleProviderStatus=ok, got "
            f"{board.get('scheduleProviderStatus')!r} — would mask provider failure",
            file=sys.stderr,
        )
        sys.exit(1)
    if board.get("rawGameCountBeforeFiltering", 0) != 0:
        print(
            f"  ✗ board.json NoGames mode requires rawGameCount=0, got "
            f"{board.get('rawGameCountBeforeFiltering')}",
            file=sys.stderr,
        )
        sys.exit(1)
    # Phase 7B-2.1: NoGames cannot mask single-source empties.
    # Require AT LEAST 2 providers in scheduleProviderHistory to have
    # status=ok with games=0. This catches the May 5 bug shape where
    # nba_api alone returning empty would trigger NoGames falsely.
    history = board.get("scheduleProviderHistory") or []
    confirmed_empty = sum(
        1 for h in history
        if isinstance(h, dict)
        and h.get("status") == "ok"
        and h.get("games", 0) == 0
    )
    if confirmed_empty < 2:
        print(
            f"  ✗ board.json NoGames mode requires AT LEAST 2 providers to "
            f"independently confirm zero games — got {confirmed_empty}. "
            f"history={history!r}",
            file=sys.stderr,
        )
        sys.exit(1)
    # And reject any "scheduleProviderStatus=empty" — the old buggy state
    # used "empty" to mean "single provider returned 0". That is now
    # ScheduleUnavailable, not NoGames.
    if board.get("scheduleProviderStatus") == "empty":
        print(
            "  ✗ board.json NoGames cannot have scheduleProviderStatus='empty' "
            "— that meant single-source confirmation in the old logic, which "
            "is now ScheduleUnavailable",
            file=sys.stderr,
        )
        sys.exit(1)

# Phase 7B-1.2: ScheduleUnavailable requires fetch failure or single-source empty
if board["dataMode"] == "ScheduleUnavailable":
    history = board.get("scheduleProviderHistory") or []
    confirmed_empty = sum(
        1 for h in history
        if isinstance(h, dict)
        and h.get("status") == "ok"
        and h.get("games", 0) == 0
    )
    # ScheduleUnavailable is valid if EITHER fetch failed OR if confirmed_empty
    # is exactly 1 (single-source empty — uncertain). Both NoGames and
    # ScheduleLiveOddsUnavailable take precedence when applicable.
    if board.get("scheduleFetchSucceeded") and confirmed_empty >= 2:
        print(
            "  ✗ board.json ScheduleUnavailable but 2+ providers confirmed "
            "empty — should be NoGames",
            file=sys.stderr,
        )
        sys.exit(1)

# ----------------------------------------------------------------------
# Phase 7B-2 — odds provider contract checks
# ----------------------------------------------------------------------
valid_odds_status = {
    None, "not_configured", "ok_with_props", "ok_no_props", "failed", "demo",
    "dry_run",
}
if board.get("oddsProviderStatus") not in valid_odds_status:
    print(
        f"  ✗ board.json oddsProviderStatus '{board.get('oddsProviderStatus')}' "
        f"not in {valid_odds_status}",
        file=sys.stderr,
    )
    sys.exit(1)

# Live mode requires real props AND oddsProviderStatus = ok_with_props
if board["dataMode"] == "Live":
    if board.get("oddsProviderStatus") != "ok_with_props":
        print(
            f"  ✗ board.json Live mode requires oddsProviderStatus=ok_with_props, "
            f"got {board.get('oddsProviderStatus')!r}",
            file=sys.stderr,
        )
        sys.exit(1)
    if not board.get("propsAvailable"):
        print(
            "  ✗ board.json Live mode requires propsAvailable=true",
            file=sys.stderr,
        )
        sys.exit(1)
    if board.get("parsedPropCount", 0) == 0:
        print(
            "  ✗ board.json Live mode requires parsedPropCount > 0",
            file=sys.stderr,
        )
        sys.exit(1)

# ok_no_props requires fetch succeeded with zero parsed props
if board.get("oddsProviderStatus") == "ok_no_props":
    if not board.get("oddsFetchSucceeded"):
        print(
            "  ✗ board.json ok_no_props requires oddsFetchSucceeded=true",
            file=sys.stderr,
        )
        sys.exit(1)
    if board.get("parsedPropCount", 0) != 0:
        print(
            f"  ✗ board.json ok_no_props requires parsedPropCount=0, "
            f"got {board.get('parsedPropCount')}",
            file=sys.stderr,
        )
        sys.exit(1)

# failed status requires either an explicit error reason OR fetch_attempted=true with failure
if board.get("oddsProviderStatus") == "failed":
    if not board.get("oddsFetchAttempted"):
        print(
            "  ✗ board.json oddsProviderStatus=failed but oddsFetchAttempted=false",
            file=sys.stderr,
        )
        sys.exit(1)
    if board.get("oddsFetchSucceeded"):
        print(
            "  ✗ board.json oddsProviderStatus=failed but oddsFetchSucceeded=true",
            file=sys.stderr,
        )
        sys.exit(1)

# Honesty rule: real-schedule modes must NOT have demo prop cards
if board["dataMode"] in ("Live", "ScheduleLiveOddsUnavailable", "NoGames", "ScheduleUnavailable"):
    if board.get("isDemo"):
        print(f"  ✗ board.json dataMode={board['dataMode']} but isDemo=true — violation", file=sys.stderr)
        sys.exit(1)
    for lean in board.get("leans", []):
        if lean.get("isDemo"):
            print(f"  ✗ real-mode board contains a demo lean: {lean.get('id')}", file=sys.stderr)
            sys.exit(1)

# Demo mode boards must explicitly tag leans isDemo=true
if board["dataMode"] == "DemoForced":
    for lean in board.get("leans", []):
        if not lean.get("isDemo"):
            print(f"  ✗ demo-mode board has lean without isDemo flag: {lean.get('id')}", file=sys.stderr)
            sys.exit(1)

# Each lean must have the fields PropCard reads
required_lean = [
    "id", "date", "tipoff", "playerId", "playerName", "team", "opponent",
    "homeAway", "market", "line", "oddsOver", "oddsUnder",
    "projection", "modelProbability", "impliedProbability", "edgePct",
    "lean", "confidence", "reason", "status",
]
if board.get("leans"):
    sample = board["leans"][0]
    missing = [k for k in required_lean if k not in sample]
    if missing:
        print(f"  ✗ board.json lean missing keys: {missing}", file=sys.stderr)
        sys.exit(1)

# trends.json must have players list
trends = json.load(open("app/public/data/trends.json"))
if not isinstance(trends.get("players"), list):
    print("  ✗ trends.json missing 'players' list", file=sys.stderr)
    sys.exit(1)

# slate.json shape
slate = json.load(open("app/public/data/slate.json"))
required_slate = ["generatedAt", "primaryDate", "slateDays", "days",
                  "newsSignalsActive", "newsSignalsConfigured"]
missing = [k for k in required_slate if k not in slate]
if missing:
    print(f"  ✗ slate.json missing keys: {missing}", file=sys.stderr)
    sys.exit(1)
if not isinstance(slate.get("days"), list) or len(slate["days"]) == 0:
    print("  ✗ slate.json days is empty", file=sys.stderr)
    sys.exit(1)

required_day = ["date", "dayLabel", "isAvailable", "gameCount", "leanCount",
                "isPrimary", "isDemo", "dataMode"]
for d in slate["days"]:
    missing = [k for k in required_day if k not in d]
    if missing:
        print(f"  ✗ slate day {d.get('date')} missing keys: {missing}", file=sys.stderr)
        sys.exit(1)
    if d["dataMode"] not in valid_modes:
        print(f"  ✗ slate day {d.get('date')} has invalid dataMode {d['dataMode']}", file=sys.stderr)
        sys.exit(1)

# Per-date board files
for d in slate["days"]:
    p = f"app/public/data/boards/{d['date']}.json"
    if not os.path.exists(p):
        print(f"  ✗ missing per-date board: {p}", file=sys.stderr)
        sys.exit(1)
    try:
        json.load(open(p))
    except json.JSONDecodeError as e:
        print(f"  ✗ {p} does not parse: {e}", file=sys.stderr)
        sys.exit(1)

# Exactly one primary
primary_days = [d for d in slate["days"] if d.get("isPrimary")]
if len(primary_days) != 1:
    print(f"  ✗ slate has {len(primary_days)} primary days (expected 1)", file=sys.stderr)
    sys.exit(1)

print(f"  ✓ meta.json has {len(required_meta)} required keys")
print(f"  ✓ meta.json providerStatuses: {len(meta['providerStatuses'])} entries")
print(f"  ✓ board.json dataMode: {board['dataMode']}")
print(f"  ✓ board.json has {len(board.get('leans', []))} leans (real/demo separation enforced)")
print(f"  ✓ trends.json has {len(trends['players'])} players")
print(f"  ✓ slate.json: {slate['slateDays']} days, primary={slate['primaryDate']}")
print(f"  ✓ per-date boards: {len(slate['days'])} files present")
print(f"  ✓ news signals: configured={slate['newsSignalsConfigured']}, active={slate['newsSignalsActive']}")
PYEOF

# ---------------------------------------------------------------------------
# 5. Public-facing files exist
# ---------------------------------------------------------------------------
echo ""
echo "[5/5] Required public files"

REQUIRED_PUBLIC=(
    "README.md"
    "LICENSE"
    ".env.example"
    ".gitignore"
    "app/package.json"
    "app/tsconfig.json"
    "app/next.config.mjs"
    "app/tailwind.config.ts"
    "pipeline/requirements.txt"
    "scripts/run_pipeline.sh"
    "docs/deploy.md"
    "docs/project_brief.md"
    "docs/portfolio_integration.md"
    "docs/screenshots.md"
    "docs/social_templates.md"
    "docs/news_overrides.md"
)

for f in "${REQUIRED_PUBLIC[@]}"; do
    if [ -f "$f" ]; then
        ok "$f"
    else
        err "missing: $f"
    fi
done

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "=========================================="
echo "  smoke test PASSED"
echo "=========================================="
echo ""
info "next: cd app && npm run typecheck && npm run build"
echo ""
